#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Русский values-ru/strings.xml для форка Telegram X (Parvane).

Источники (по приоритету):
  1. ru-hand.py — ручной словарь по ключам X;
  2. русский перевод десктопа (desktop/langs/parvane_ru_RU.strings) по СОВПАДЕНИЮ
     английского текста с tdesktop lang.strings (ключи у tdesktop и X разные).
Строки с плейсхолдерами берём только если набор %N$s/%d совпадает с английским —
иначе String.format уронит приложение. Вызов: gen-ru.py <tgx-dir> [repo-root].
"""
import html, json, os, re, sys

TGX = sys.argv[1]
ROOT = sys.argv[2] if len(sys.argv) > 2 else os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ru_hand import RU as HAND  # noqa: E402  (словарь — ru_hand.py рядом)

def load_strings(p):
    d = {}
    for line in open(p, encoding="utf-8"):
        m = re.match(r'^"([^"]+)"\s*=\s*"(.*)";\s*$', line.rstrip("\n"))
        if m:
            d[m.group(1)] = m.group(2).replace('\\"', '"')
    return d

def norm(s):
    return re.sub(r"\s+", " ", s.replace("…", "...").strip()).lower()

FMT = re.compile(r"%(\d+\$)?[sd]")
def fmt_tokens(s):
    return sorted(FMT.findall(s))

en = load_strings(os.path.join(ROOT, "desktop/tdesktop/Telegram/Resources/langs/lang.strings"))
ru = load_strings(os.path.join(ROOT, "desktop/langs/parvane_ru_RU.strings"))
en2ru = {}
for k, v in en.items():
    r = ru.get(k)
    if r and r != v and not re.search(r"\{[a-z_]+\}", v):
        en2ru.setdefault(norm(v), r)

src = os.path.join(TGX, "app/src/main/res/values/strings.xml")
xml = open(src, encoding="utf-8").read()
items = re.findall(r'<string name="([^"]+)"([^>]*)>(.*?)</string>', xml, re.S)

def esc(s):
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    s = s.replace("'", "\\'").replace('"', '\\"')
    return s

out, n_hand, n_desk = [], 0, 0
for key, attrs, val in items:
    plain = html.unescape(val).replace("\\'", "'").replace('\\"', '"')
    tr = HAND.get(key)
    if tr is not None:
        n_hand += 1
    else:
        tr = en2ru.get(norm(plain))
        if tr is None:
            continue
        n_desk += 1
    if fmt_tokens(tr) != fmt_tokens(plain):
        continue  # разный набор плейсхолдеров — опасно
    # текст десктопа: markdown **…** такой же, {emoji} не бывает (отфильтровано)
    out.append(f'    <string name="{key}"{attrs}>{esc(tr)}</string>')

# Русские правила множественного числа у X: one/few/many/other. Для встроенного языка X
# ищет ресурсы key_few/key_many и падает (NotFoundException resId==0), если их нет.
# Добавляем few/many = other (наши _other нейтральны: «Чатов: %1$s») и английские
# значения по умолчанию в values/ — ресурс не может существовать только в values-ru.
tr_map = {}
for line in out:
    m = re.match(r'    <string name="([^"]+)"[^>]*>(.*)</string>$', line, re.S)
    tr_map[m.group(1)] = line
en_items = {k: (attrs, v) for k, attrs, v in items}
extra_ru, extra_en = [], []
for key in en_items:  # ВСЕ плюралы X, не только переведённые: в ru-локали X ищет few/many у каждого
    if not key.endswith("_other"):
        continue
    base = key[:-6]
    for form in ("_few", "_many"):
        if base + form in en_items:
            continue
        attrs, v = en_items[key]
        extra_en.append(f'    <string name="{base}{form}"{attrs}>{v}</string>')
        if key in tr_map:
            extra_ru.append(tr_map[key].replace(f'name="{key}"', f'name="{base}{form}"', 1))
out += extra_ru
with open(os.path.join(TGX, "app/src/main/res/values/strings_ru_plurals.xml"), "w", encoding="utf-8") as f:
    f.write('<?xml version="1.0" encoding="utf-8"?>\n<!-- generated by android/tgx-overlay/gen-ru.py: формы few/many для русских правил (по умолчанию = английский other) -->\n<resources>\n')
    f.write("\n".join(extra_en))
    f.write("\n</resources>\n")

dst_dir = os.path.join(TGX, "app/src/main/res/values-ru")
os.makedirs(dst_dir, exist_ok=True)
with open(os.path.join(dst_dir, "strings.xml"), "w", encoding="utf-8") as f:
    f.write('<?xml version="1.0" encoding="utf-8"?>\n<!-- generated by android/tgx-overlay/gen-ru.py — не править руками -->\n<resources>\n')
    f.write("\n".join(out))
    f.write("\n</resources>\n")
print(f"   values-ru: {len(out)} строк (ручных {n_hand}, из десктопа {n_desk}, форм few/many {len(extra_ru)}) из {len(items)}")
