# -*- coding: utf-8 -*-
# Ручной русский перевод строк Telegram X (Parvane), которых нет в словаре десктопа
# (desktop/langs/parvane_ru_RU.strings по совпадению английского текста).
# Ключи — имена <string name="…"> из app/src/main/res/values/strings.xml форка X.
# Плюралы: у X только формы _one/_other (правила «en»), поэтому _other пишем
# нейтрально («Чатов: %1$s»), чтобы не было «2 чатов». Плейсхолдеры %1$s сохраняем.
RU = {
    # ── метаданные встроенного пака: с values-ru X считает встроенный язык русским
    # (Lang.getBuiltinLanguagePackId() = R.string.language_code), плюралы — по правилам ru
    "language_code": "ru",
    "language_name": "Русский",
    "language_nameInEnglish": "Russian",
    "language_emoji": "\U0001F1F7\U0001F1FA",
    "language_dateFormatLocale": "ru-RU",
    "language_rtl": "0",
    "language_continueInLanguage": "Продолжить на русском",
    # ── общее ──
    "Message": "Сообщение",  # словарь десктопа давал «Чат» — подсказка поля ввода
    "NotificationsEnabled": "Включены", "NotificationsDisabled": "Выключены",
    "NotificationsDefaultEnabled": "Включены", "NotificationsDefaultDisabled": "Выключены",
    "NoMediaToShow": "Нет медиа",
    "NoMediaToShowInChat": "Делитесь фото и видео в этом чате —\nони будут доступны на всех ваших устройствах.",
    "SoundDisabled": "Выключен", "VibrateDisabled": "Выключена", "LedDisabled": "Выключен",
    "RingtoneDisabled": "Выключен", "RepeatNotificationsDisabled": "Выключено", "AutoNightDisabled": "Выключен",
    "ReactionsAllowNone": "Выключены", "QuickReactionDisabled": "Выключена", "NotificationImportanceNone": "Выключены",
    "CategoryMuted": "Без звука", "PinnedDisabled": "Выключены", "MentionsDisabled": "Выключены",
    "MessagePreviewDisabled": "Выключен", "PasscodeSettingDisabled": "Выключен", "AutoLockDisabled": "Выключена",
    "LoadingInformation": "Загрузка…",
    "LoadingUsername": "Загрузка имени пользователя…",
    "LoadingUser": "Загрузка пользователя…",
    "LoadingPhone": "Загрузка телефона…",
    "Calculating": "Подсчёт…",
    "CopiedText": "Текст скопирован в буфер обмена",
    "CopiedLink": "Ссылка скопирована в буфер обмена",
    "CopiedLinkPrivate": "Ссылка скопирована. Она работает только для участников этого чата.",
    "CopiedUsername": "Имя пользователя скопировано в буфер обмена",
    "CopiedPeerId": "ID скопирован в буфер обмена",
    "CopiedMyUserId": "Ваш ID скопирован в буфер обмена",
    "CopiedMessages": "Сообщения скопированы в буфер обмена",
    "CopyVersion": "Скопировать версию",
    "IsDefault": "%1$s (по умолчанию)",
    "NeverShowAgain": "Больше не показывать",
    "NoUndoWarn": "Это действие нельзя отменить.",
    "NoAppToOpen": "Не найдено приложение, чтобы открыть этот файл",
    "NoStorageAccess": "Для этой функции нужен доступ к хранилищу.",
    "SelectMore": "Выбрать…",
    "TapToSetup": "Нажмите, чтобы задать",
    "SetBirthdate": "Нажмите, чтобы задать",
    "SetUpUsername": "Задать имя пользователя",
    "PhoneNumberUnknown": "Неизвестен",
    "NumberHidden": "Номер неизвестен",
    "YourAccount": "Ваш аккаунт",
    "CurrentAccount": "%1$s (текущий)",
    "UserId": "ID пользователя",
    "PeerId": "ID чата",
    "BasicGroupId": "ID группы",
    "SuperGroupId": "ID супергруппы",
    "Beginning": "Начало",
    "Follow": "Подписаться",
    "Long": "Длинная",
    "DoubleShort": "Двойная короткая",
    "Vibrate": "Вибрация",
    "Ringtone": "Рингтон",
    "Gallery": "Галерея",
    "Wallpaper": "Обои",
    "Caption": "Подпись",
    "FileName": "Имя файла",
    "FileNameCopy": "%1$s (копия)",
    "FileNameDuplicate": "%1$s #%2$d",
    "Connection": "Соединение",
    "TermsOfServiceDone": "Принять",
    "login_LastName": "Фамилия (необязательно)",
    "ShowContacts": "Начать чат",
    "InviteContacts": "Пригласить контакты",
    "NoContacts": "Нет контактов",
    "EncryptionKey": "Ключ шифрования",
    "PictureAndText": "Картинка и текст",
    "AwaitingEncryption": "Ждём, когда %1$s появится в сети…",
    "SendMessageTo": "Отправить сообщение…",
    "SendAs": "Отправить от имени",
    "PostedBy": "Опубликовал %1$s",
    "CreatedByXOnDate": "Создал %1$s %2$s",
    "ForwardedFromX": "Переслано от %1$s",
    "InReplyToX": "В ответ на %1$s",
    "AnotherChatReplyHint": "Сообщение из другого чата. Нажмите ещё раз, чтобы посмотреть.",
    "ReplyRequiredHint": "Выберите сообщение для ответа",
    "SendFailureInfo": "Не отправлено: %1$s",
    "ProcessingFileWait": "Обработка файлов. Подождите…",
    "SlowFileAccess": "Медленный доступ к файлам. Сообщение уйдёт после чтения файлов",
    "DetectLocationError": "Не удалось определить текущее местоположение.",
    "ShareYourLocation": "Поделиться местоположением?",
    "ShareYouLocationUnableManually": "Выбрать вручную",
    "MediaSpoilerHint": "Медиа будет размыто в чате и откроется по дополнительному нажатию.",
    "MediaRestricted": "Медиа недоступно",
    "ShareContentUnsupported": "Этот тип медиа пока не поддерживается.",
    "ShareContact": "Поделиться контактом",
    "ShareMyContactInfo": "Поделиться моим контактом",
    "SharePhoneNumber": "Поделиться номером",
    "ShareMyNumber": "Поделиться моим номером с %1$s",
    "ShareYourPhoneNumberTitle": "Поделиться номером телефона?",
    "ShareYourPhoneNumberDesc": "%1$s узнает ваш номер телефона.",
    "ShareTextLink": "Смотрите %1$s: %2$s",
    "ShareTextChatLink": "Присоединяйтесь к «%1$s» в Parvane: %2$s",
    "ShareTextProfileLink": "%1$s в Parvane: %2$s",
    "ShareTextProfileLink2": "Контакт %1$s: %2$s",
    "RenameContact": "Переименовать контакт",
    "UnknownChats": "Чаты от незнакомых пользователей",
    "MessagesArchive": "Сообщения в архивных чатах",
    "HoldToVideo": "Удерживайте, чтобы записать видео. Нажмите, чтобы переключиться на аудио.",
    "HoldToAudio": "Удерживайте, чтобы записать аудио. Нажмите, чтобы переключиться на видео.",
    "HoldToPreview": "Предпросмотр чатов",
    "HoldToSchedule": "Удерживайте, чтобы отправить в заданное время и другие варианты.",
    "HoldToSchedule2": "Удерживайте, чтобы отправить, когда %1$s появится в сети, и другие варианты.",
    "HoldToRemind": "Удерживайте, чтобы создать напоминание.",
    "HoldToSilentBroadcast": "Удерживайте для отправки без звука и других вариантов.",
    "SwipeToSwapLinkPreview": "Свайп — выбрать другой предпросмотр ссылки",
    "LinkPreviewShowBelow": "Предпросмотр ссылки будет под текстом",
    "LinkPreviewShowAbove": "Предпросмотр ссылки будет над текстом",
    "LinkPreviewMinimized": "Медиа предпросмотра будет уменьшено",
    "LinkPreviewEnlarged": "Медиа предпросмотра будет увеличено",
    "DiscardEditMsg": "Отменить правку",
    "DiscardEditMsgHint": "Отменить правку сообщения? Изменения будут потеряны.",
    "DiscardEditCaption": "Отменить подпись",
    "DiscardEditCaptionHint": "Отменить правку подписи? Изменения будут потеряны.",
    "DiscardCaptionHint": "Убрать подпись? Изменения будут потеряны.",
    "DraftPreFillWarning": "Ваш прежний черновик в этом чате будет заменён.",
    "EditMarkdown": "Разметка",
    "EditMarkdownHint2": "Форматирование текста: `**`**жирный**`**`, `__`__курсив__`__`, `~~`~~зачёркнутый~~`~~`, ````моноширинный````, `||`||спойлер||`||`, `[`текст`](`ссылка`)`",
    "EditMediaRestricted": "Нельзя изменить тип медиа",
    "EditMessageTextTooLong_one": "Текст длиннее лимита на %1$s символ.",
    "EditMessageTextTooLong_other": "Текст длиннее лимита на %1$s символов.",
    "EditMessageCaptionTooLong_one": "Подпись длиннее лимита на %1$s символ.",
    "EditMessageCaptionTooLong_other": "Подпись длиннее лимита на %1$s символов.",
    "SelectUnread": "Выбрать непрочитанные",
    "SelectMuted": "Выбрать без звука",
    "SelectChat": "Выберите чат",
    "SelectMessagesInBetween": "Выбрать сообщения между",
    "SendXMessagesNow_one": "Отправить %1$s сообщение?",
    "SendXMessagesNow_other": "Отправить сообщения (%1$s)?",
    "ResendXMessages_one": "Отправить заново %1$s сообщение",
    "ResendXMessages_other": "Отправить заново сообщения (%1$s)",
    "ForwardLastXMessages_one": "Переслать последнее сообщение",
    "ForwardLastXMessages_other": "Переслать последние сообщения (%1$s)",
    "YouCantForwardMoreMessages_one": "Нельзя переслать больше %1$s сообщения за раз",
    "YouCantForwardMoreMessages_other": "Нельзя переслать больше %1$s сообщений за раз",
    "AsOneMessage": "одним сообщением",
    "AsSeparateMessages": "отдельными сообщениями",
    "AsXMessages_one": "как %1$s сообщение",
    "AsXMessages_other": "как %1$s сообщений",
    "SelectedSuffix_one": " выбрано",
    "SelectedSuffix_other": " выбрано",
    "AttachVideosSuffix_one": " видео",
    "AttachVideosSuffix_other": " видео",
    "AttachPhotosSuffix_one": " фото",
    "AttachPhotosSuffix_other": " фото",
    "AttachMediasSuffix_one": " медиа",
    "AttachMediasSuffix_other": " медиа",
    "RememberAlbumSetting": "Запоминать настройку группировки медиа",
    "MessageSearchFilterText": "Текстовые сообщения",
    "MessageSearchFilterAll": "Все типы сообщений",
    "FoundMessagesQuery": "%1$s",
    "FoundMessagesFromUser": "сообщения от %1$s",
    "FoundMessagesFromSelf": "сообщения от вас",
    "FoundMessagesFromChat": "сообщения из %1$s",
    "XFoundMessagesFromUser_one": "%1$s сообщение от %2$s",
    "XFoundMessagesFromUser_other": "Сообщений от %2$s: %1$s",
    "XFoundMessagesFromSelf_one": "%1$s сообщение от вас",
    "XFoundMessagesFromSelf_other": "Сообщений от вас: %1$s",
    "XFoundMessagesFromChat_one": "%1$s сообщение из %2$s",
    "XFoundMessagesFromChat_other": "Сообщений из %2$s: %1$s",
    # ── счётчики ──
    "xMinutes_one": "%1$s минута", "xMinutes_other": "%1$s мин.",
    "xHours_one": "%1$s час", "xHours_other": "%1$s ч.",
    "xMembers_one": "%1$s участник", "xMembers_other": "Участников: %1$s",
    "xGroups_one": "%1$s группа", "xGroups_other": "Групп: %1$s",
    "xChats_one": "%1$s чат", "xChats_other": "Чатов: %1$s",
    "xPhotos_one": "%1$s фото", "xPhotos_other": "Фото: %1$s",
    "xVideos_one": "%1$s видео", "xVideos_other": "Видео: %1$s",
    "xFiles_one": "%1$s файл", "xFiles_other": "Файлов: %1$s",
    "xLinks_one": "%1$s ссылка", "xLinks_other": "Ссылок: %1$s",
    "xMedia_one": "%1$s медиа", "xMedia_other": "Медиа: %1$s",
    "xGIFs_one": "%1$s GIF", "xGIFs_other": "GIF: %1$s",
    "xAudios_one": "%1$s аудио", "xAudios_other": "Аудио: %1$s",
    "xVoiceMessages_one": "%1$s голосовое сообщение", "xVoiceMessages_other": "Голосовых: %1$s",
    "xVideoMessages_one": "%1$s видеосообщение", "xVideoMessages_other": "Видеосообщений: %1$s",
    "xViews_one": "%1$s просмотр", "xViews_other": "Просмотров: %1$s",
    "xReacted_one": "%1$s реакция", "xReacted_other": "Реакций: %1$s",
    "XPinnedMessages_one": "%1$s закреплённое сообщение", "XPinnedMessages_other": "Закреплённых: %1$s",
    "xAdmins_one": "%1$s администратор", "xAdmins_other": "Администраторов: %1$s",
    "xBanned_one": "%1$s заблокирован", "xBanned_other": "Заблокировано: %1$s",
    "xOtherUsernames_one": "ещё %1$s", "xOtherUsernames_other": "ещё %1$s",
    "xPermissions_one": "%1$s из %2$s", "xPermissions_other": "%1$s из %2$s",
    "xActiveLinks_one": "%1$s активная ссылка", "xActiveLinks_other": "Активных ссылок: %1$s",
    "xRevokedLinks_one": "%1$s отозванная ссылка", "xRevokedLinks_other": "Отозванных ссылок: %1$s",
    "xJoinRequests_one": "%1$s заявка", "xJoinRequests_other": "Заявок: %1$s",
    "ReadDate_now": "Прочитано только что",
    "ReadDate_seconds_one": "Прочитано %1$s секунду назад", "ReadDate_seconds_other": "Прочитано %1$s сек. назад",
    "ReadDate_minutes_one": "Прочитано %1$s минуту назад", "ReadDate_minutes_other": "Прочитано %1$s мин. назад",
    "ReadDate_hours_one": "Прочитано %1$s час назад", "ReadDate_hours_other": "Прочитано %1$s ч. назад",
    "ReadDate_today": "Прочитано в %1$s",
    "ReadDate_yesterday": "Прочитано вчера в %1$s",
    "ReadDate_weekday": "Прочитано %1$s в %2$s",
    "ReadDate_date": "Прочитано %1$s в %2$s",
    # ── список чатов, массовые действия ──
    "DragChatsHint": "Перетащите чат, чтобы изменить порядок",
    "HideAllChats": "Скрыть все чаты",
    "NoArchive": "Архив пуст",
    "OpenArchiveHint": "**Нет чатов**\n\nВсе ваши чаты в архиве",
    "ArchiveRead": "Прочитать все",
    "ArchivePin": "Закрепить в списке чатов",
    "ArchiveHide": "Скрыть из списка чатов",
    "ArchiveSettingsDesc": "Какие чаты остаются в архиве, даже если у них включён звук и пришло новое сообщение.",
    "ArchiveXChats_one": "Архивировать %1$s чат", "ArchiveXChats_other": "Архивировать чаты (%1$s)",
    "ArchivedXChats_one": "Архивирован %1$s чат", "ArchivedXChats_other": "Архивировано чатов: %1$s",
    "UnarchiveXChats_one": "Вернуть из архива %1$s чат", "UnarchiveXChats_other": "Вернуть из архива чаты (%1$s)",
    "UnarchivedXChats_one": "Возвращён из архива %1$s чат", "UnarchivedXChats_other": "Возвращено из архива чатов: %1$s",
    "MuteXChats_one": "Выключить звук в %1$s чате", "MuteXChats_other": "Выключить звук в чатах (%1$s)",
    "MutedXChats_one": "Звук выключен в %1$s чате", "MutedXChats_other": "Звук выключен в чатах: %1$s",
    "UnmutedXChats_one": "Звук включён в %1$s чате", "UnmutedXChats_other": "Звук включён в чатах: %1$s",
    "EnableNotifications2_one": "Включить звук в %1$s чате", "EnableNotifications2_other": "Включить звук в чатах (%1$s)",
    "NotificationsOnXChats_one": "Уведомления включены для %1$s чата", "NotificationsOnXChats_other": "Уведомления включены для чатов: %1$s",
    "PinXChats_one": "Закрепить %1$s чат", "PinXChats_other": "Закрепить чаты (%1$s)",
    "UnpinXChats_one": "Открепить %1$s чат", "UnpinXChats_other": "Открепить чаты (%1$s)",
    "PinToTop": "Закрепить",
    "UnpinFromTop": "Открепить",
    "PinTooMuchWarn_one": "В основном списке можно закрепить только %1$s чат. Архивируйте часть чатов — в архиве закреплять можно без ограничений.",
    "PinTooMuchWarn_other": "В основном списке можно закрепить только %1$s чатов. Архивируйте часть чатов — в архиве закреплять можно без ограничений.",
    "MarkedXChats_one": "%1$s чат отмечен непрочитанным", "MarkedXChats_other": "Отмечено непрочитанными чатов: %1$s",
    "ReadAllChatsDone_one": "%1$s чат отмечен прочитанным", "ReadAllChatsDone_other": "Отмечено прочитанными чатов: %1$s",
    "DeleteXChats_one": "Удалить %1$s чат", "DeleteXChats_other": "Удалить чаты (%1$s)",
    "DeleteXChatsConfirm_one": "Удалить %1$s чат?", "DeleteXChatsConfirm_other": "Удалить чаты (%1$s)?",
    "DeletedXChats_one": "Удалён %1$s чат", "DeletedXChats_other": "Удалено чатов: %1$s",
    "ClearXChats_one": "Очистить медиа в %1$s чате? Медиа придётся скачать заново.", "ClearXChats_other": "Очистить медиа в чатах (%1$s)? Медиа придётся скачать заново.",
    "ClearingXChats_one": "Очистка медиа в %1$s чате… Это может занять время.", "ClearingXChats_other": "Очистка медиа в чатах (%1$s)… Это может занять время.",
    "ClearedSizeChats_one": "Очищено %2$s в %1$s чате", "ClearedSizeChats_other": "Очищено %2$s в чатах: %1$s",
    "ClearedNoneChats_one": "Нечего очищать в %1$s чате", "ClearedNoneChats_other": "Нечего очищать в чатах: %1$s",
    "LeaveXChats_one": "Вы не сможете вернуться в %1$s чат", "LeaveXChats_other": "Вы не сможете вернуться в чаты: %1$s",
    "LeaveXPrivateGroup_one": "Вы не сможете вернуться в %1$s группу", "LeaveXPrivateGroup_other": "Вы не сможете вернуться в группы: %1$s",
    "BlockXUsers_one": "Заблокировать %1$s пользователя", "BlockXUsers_other": "Заблокировать пользователей (%1$s)",
    "BlockedXUsers_one": "Заблокирован %1$s пользователь", "BlockedXUsers_other": "Заблокировано пользователей: %1$s",
    "UnblockedXUsers_one": "Разблокирован %1$s пользователь", "UnblockedXUsers_other": "Разблокировано пользователей: %1$s",
    "BlockUserConfirm": "Заблокировать %1$s?",
    "BlockedUser": "%1$s заблокирован(а).",
    "UnblockedUser": "%1$s разблокирован(а).",
    "ReportedXChats_one": "Жалоба отправлена на %1$s чат", "ReportedXChats_other": "Жалобы отправлены на чаты: %1$s",
    "ReportChatSpam": "Пожаловаться на %1$s за спам?",
    "RevokeForX_one": "Удалить все сообщения и у %1$s собеседника", "RevokeForX_other": "Удалить все сообщения и у собеседников (%1$s)",
    # ── закреплённые, реакции ──
    "PinMessageInChat": "Закрепить это сообщение?",
    "PinMessageInThisGroup": "Закрепить это сообщение в группе?",
    "PinMessageOther": "Закрепить и для %1$s",
    "PinNotify2": "Уведомить всех участников",
    "UnpinMessage": "Открепить сообщение",
    "UnpinAll": "Открепить все сообщения",
    "UnpinXMessages_one": "Открепить %1$s сообщение?", "UnpinXMessages_other": "Открепить сообщения (%1$s)?",
    "DismissAllPinned": "Скрыть все сообщения",
    "HideForYourself": "Скрыть для себя",
    "PinnedEnabled": "Включено",
    "ReactionsAllowAll": "Включены",
    "ReactionsAllowSome_one": "Разрешена %1$s", "ReactionsAllowSome_other": "Разрешено: %1$s",
    "MentionsEnabled": "Включены",
    "MessagePreviewEnabled": "Включён",
    # ── вкладки профиля ──
    "TabEmptyPhotos": "Нет фото",
    "TabEmptyMedias": "Нет медиа",
    "TabEmptyLinks": "Нет ссылок",
    "TabEmptyDocs": "Нет документов",
    "NoPhotos": "Нет фото",
    "NoVideos": "Нет видео",
    "NoFiles": "Нет файлов",
    "NoGIFs": "Нет GIF",
    "NoMusic": "Нет музыки",
    "NoVoiceMessages": "Нет голосовых сообщений",
    "NoVideoMessages": "Нет видеосообщений",
    "NoFilter": "Без фильтра",
    "SeparateMediaTab": "Раздельные вкладки фото и видео",
    # ── группы ──
    "BanMember": "Заблокировать участника",
    "ViewAdmins": "Администраторы",
    "DestroyGroup": "Удалить группу",
    "DestroyGroupHint": "Удаление группы уберёт всех участников, все сообщения будут потеряны. Удалить группу?",
    "DestroyXNoMembers": "Удалить %1$s?",
    "DestroyX_one": "Удалить %2$s? Группа исчезнет у вас и ещё у %1$s участника.",
    "DestroyX_other": "Удалить %2$s? Группа исчезнет у вас и у остальных участников (%1$s).",
    "AddToTheGroup": "Добавить %1$s в группу?",
    "AddAdminToTheGroup": "Добавить %1$s в группу и назначить администратором?",
    "justAdd": "Просто добавить в группу",
    "GroupDontAdd": "Не добавлять в группу",
    "GroupEnterValidName": "Введите корректное название группы",
    "ChatTitleEmpty": "Название чата не может быть пустым",
    "ChatPermissions": "Права участников",
    "MemberCannotJoinGroup": "%1$s не сможет вернуться в группу, пока администратор не добавит снова.",
    "XIsAlreadyInChat": "%1$s уже участник этого чата",
    "XIsAlreadyAdmin": "%1$s уже администратор",
    "ParticipantXLimitReached_one": "В группу нельзя добавить больше %1$s участника",
    "ParticipantXLimitReached_other": "В группу нельзя добавить больше %1$s участников",
    "YouCantPromoteX": "Недостаточно прав, чтобы назначить %1$s администратором.",
    "YouCantBanX": "Недостаточно прав, чтобы заблокировать %1$s.",
    "LosingXAdminRights_one": "Вы потеряете права администратора в %1$s чате", "LosingXAdminRights_other": "Вы потеряете права администратора в чатах: %1$s",
    "GroupLink": "Ссылка группы",
    "GroupLinkSet": "Нажмите, чтобы задать публичную ссылку",
    "LinkedGroup": "Связанная группа",
    "OnlyOwnerGroup": "Только владелец группы может менять эту настройку.",
    "HideMembersDesc": "Скрыть список участников группы. Администраторы останутся видны.",
    "ApproveNewMembersInfo": "Новые участники будут вступать только после одобрения администратором.",
    "RequestJoinGroup": "Запросить вступление",
    "AnonWarning": "Это действие раскроет ваш личный аккаунт. Нажмите ещё раз для подтверждения.",
    "ChatTtlEnabled": "Новые сообщения автоматически удаляются через %1$s у всех участников.",
    "ChatTtlDisabled": "Через какое время сообщения будут автоматически удаляться из группы.",
    "RecentActionsGroupHint": "Служебные действия в группе за последние 48 часов.",
    "MessageInputTextDisabledHint": "Администраторы запретили отправку текстовых сообщений.",
    "ChatDisabledMedia": "Только администраторы могут отправлять медиа",
    "ChatDisabledPhoto": "Только администраторы могут отправлять фото",
    "ChatDisabledVideo": "Только администраторы могут отправлять видео",
    "ChatDisabledGifs": "Только администраторы могут отправлять GIF",
    "ChatRestrictedMedia": "Администраторы запретили вам отправлять медиа.",
    "ChatRestrictedPhoto": "Администраторы запретили вам отправлять фото.",
    "ChatRestrictedVideo": "Администраторы запретили вам отправлять видео.",
    "ChatRestrictedMediaUntil": "Администраторы запретили вам отправлять медиа до %1$s",
    "ChatRestrictedPhotoUntil": "Администраторы запретили вам отправлять фото до %1$s",
    "ChatRestrictedVideoUntil": "Администраторы запретили вам отправлять видео до %1$s",
    "ChatRestrictedGifsUntil": "Администраторы запретили вам отправлять GIF до %1$s",
    "RestrictSavingUserInfo": "Копирование и пересылка этого сообщения ограничены.",
    "RestrictSavingGroupInfo": "Копирование и пересылка ограничены администраторами",
    "RestrictSavingGroupHint": "Участники не смогут копировать, сохранять и пересылать содержимое группы.",
    "errorPrivacyAddMember": "Пользователь ограничил в настройках приватности, кто может добавлять его в чаты.",
    # ── настройки: внешний вид ──
    "ThemeSettings": "Темы и чаты",
    "TweakSettings": "Интерфейс",
    "Tweaks": "Настройки интерфейса",
    "TextSize": "Размер шрифта сообщений",
    "TextSizeScaleEnable": "Включить масштабирование",
    "TextSizeScaleDisable": "Выключить масштабирование",
    "ChatMode": "Вид чатов",
    "ChatStyleBubbles": "Пузыри в чатах",
    "ChatListStyle": "Вид списка чатов",
    "ChatListStyle1": "Две строки",
    "ChatListStyle2": "Три строки",
    "ChatListStyle3": "Три строки (крупнее)",
    "ChatListStyleOptIcons": "Значки медиа",
    "ChatListStyleOptFormatting": "Форматирование текста",
    "ChatQuickActions": "Действия свайпом",
    "ChatPreview": "Предпросмотр чата",
    "ChatBackgroundPreview": "Предпросмотр обоев",
    "ChatBackgroundApply": "Применить обои",
    "ChatBackgroundTypeSolid": "сплошной цвет",
    "ChatBackgroundTypePattern": "узор",
    "ChatBackgroundTypeMulticolor": "многоцветный градиент",
    "ChatBackgroundTypeGradient": "градиент",
    "ThemeCreateTitle": "Новая тема",
    "ThemeCreateInfo": "Новая тема будет основана на теме %1$s.",
    "ThemeEditInfo": "Тема %1$s",
    "ThemeCopy": "Создать копию",
    "Icons": "Набор значков",
    "ReduceMotion": "Меньше анимации",
    "RtlLayout": "Раскладка справа налево",
    "HideChatKeyboard": "Скрывать клавиатуру при прокрутке чата",
    "UseSystemFonts": "Системные шрифты",
    "UseSystemFontsHint": "**Внимание!**\n\nParvane не гарантирует корректное отображение системных шрифтов.",
    "BatmanTransitions": "Анимация Бэтмена в опросах",
    "AutoNightMode": "Ночной режим",
    "AutoNightSystem": "Как в системе",
    "AutoNightAutomatic": "Автоматически",
    "AutoNightModeDescription": "Переключать ночную тему по освещённости или расписанию.",
    "AutoNightModeDescriptionScheduled": "Переключать ночную тему по расписанию.",
    "AutoNightModeDescriptionSystem": "Переключать ночную тему по значению из системы.",
    "AutoNightModeDescriptionSystemQ": "Переключать ночную тему по настройкам системы.",
    "AutoNightModeDescriptionAuto": "Переключать на ночную тему, когда освещённость ниже %1$d%%.\n\nТочка показывает текущий уровень освещённости, измеренный устройством.",
    "AutoNightModeScheduledByLocation": "Определять время заката и рассвета",
    "AutoNightModeScheduledByLocationProgress": "Определение местоположения…",
    "AutoNightModeScheduledByLocationPolarNight": "В вашем местоположении сейчас нет заката и рассвета.",
    "TurnOnAutomatically": "Включать автоматически",
    # ── настройки: уведомления ──
    "SystemNotificationSettings": "Системные настройки уведомлений",
    "ResetNotifications": "Сбросить все уведомления",
    "ResetNotificationsConfirm": "Сбросить все настройки уведомлений, включая индивидуальные для контактов, групп и каналов?",
    "NotificationsSettingOn": "Уведомления включены по умолчанию. Отдельные чаты можно выключить в списке чатов.",
    "NotificationsSettingOff": "Уведомления выключены по умолчанию. Отдельные чаты можно включить в списке чатов.",
    "NotificationsSettingBlocked": "Уведомления заблокированы по умолчанию. Измените «Стиль уведомлений», чтобы разблокировать.",
    "NotificationsPrivateInfo": "Индивидуальные уведомления для пользователя настраиваются в его профиле.",
    "NotificationsGroupInfo": "Индивидуальные уведомления для группы настраиваются в её профиле.",
    "NotificationsPriority": "Приоритет",
    "NotificationsLed": "Индикатор",
    "NotificationImportance": "Стиль уведомлений",
    "RepeatNotifications": "Повторять уведомления",
    "CustomNotifications": "Свои уведомления",
    "CustomNotificationsHint": "Эти настройки заменят общие из «Настройки → Уведомления».",
    "CustomVibrations": "Свои вибрации",
    "MessagePreview": "Текст сообщения",
    "MessageContentPreview": "Предпросмотр картинок",
    "Mentions": "Упоминания и ответы",
    "MentionsOn": "Применять настройки личных уведомлений к упоминаниям и ответам. Если автор без звука — уведомления не будет.",
    "MentionsOff": "Применять настройки уведомлений группы к упоминаниям и ответам. Если группа без звука — уведомления не будет.",
    "PinnedMessagesOn": "Применять настройки личных уведомлений при закреплении сообщения. Если автор без звука — уведомления не будет.",
    "PinnedMessagesOff": "Применять настройки уведомлений группы при закреплении сообщения. Если группа без звука — уведомления не будет.",
    "Prioritize": "Личные уведомления",
    "PriorityAboutUrgentAndLow": "Срочные уведомления показываются даже в режиме «Не беспокоить». Низкий приоритет — только в шторке.",
    "EventNewContact2": "Новые контакты",
    "EventNewContactInfo": "Уведомлять, когда кто-то из контактов появляется в Parvane.",
    "EventScheduledMessage": "Отправленные отложенные",
    "EventScheduledMessageDesc": "Уведомлять, когда отложенное сообщение отправлено в чат с включёнными уведомлениями.",
    "NotificationMerge": "Объединять категории уведомлений",
    "NotificationMergeOn": "Показывать уведомления из личных чатов, групп и каналов одной группой.",
    "NotificationMergeOff": "Показывать уведомления из личных чатов, групп и каналов раздельно.",
    "IncludeDismissed": "Включать скрытые сообщения",
    "IncludeDismissedHintOff": "Не включать ранее скрытые непрочитанные сообщения в новое уведомление из чата.",
    "InChatSound": "Звуки в чате",
    "InChatSoundInfo": "Звуки входящих и исходящих сообщений в открытом чате.",
    "MuteNonContacts": "Без звука от незнакомых",
    "MuteNonContactsInfo": "Уведомления от людей не из контактов будут без звука. Добавить в контакты можно из профиля, не зная номера.",
    "BadgeCounterMuted": "Считать чаты без звука",
    "BadgeCounterArchive": "Считать архивные чаты",
    "BadgeCounterMessagesOn": "Показывать число непрочитанных сообщений вместо чатов.",
    "BadgeCounterMessagesOff": "Показывать число непрочитанных чатов вместо сообщений.",
    "OnlyIfSilent": "Только в тихом режиме",
    "XOnlyIfSilent": "%1$s (только в тихом режиме)",
    "XButOnlyIfSilent": "%1$s (но только в тихом режиме)",
    "NotificationsErrorBlocked": "Заблокированы в настройках системы",
    "NotificationsErrorPermission": "Заблокированы разрешениями системы",
    "NotificationsErrorBackground": "Уведомления могут не работать при закрытом приложении",
    "NotificationsErrorError": "Не удалось показать часть уведомлений",
    "NotificationsErrorErrorChat": "Не удалось показать уведомление от %1$s",
    "NotificationsErrorBlockedPrivate": "Уведомления из личных чатов заблокированы",
    "NotificationsErrorBlockedGroup": "Уведомления из групп заблокированы",
    "NotificationsErrorBlockedMixed": "Часть уведомлений заблокирована",
    "NotificationsErrorBlockedCategory": "Уведомления этого аккаунта заблокированы",
    "NotificationsErrorUnselected": "Уведомления этого аккаунта выключены",
    "NotificationsGuideBlockedAll": "Уведомления Parvane заблокированы в настройках устройства.\n\nЧтобы включить:\n• Нажмите «Системные настройки уведомлений».\n• Включите «Показывать уведомления».",
    "NotificationsGuideBlockedApp": "Уведомления Parvane заблокированы в системе. Нажмите «Системные настройки уведомлений», чтобы разблокировать.",
    "NotificationsGuideBlockedCategory": "Уведомления текущего аккаунта выключены в системных настройках.\n\nЧтобы включить:\n• Нажмите «Системные настройки уведомлений»\n• Найдите категорию «%1$s»\n• Включите переключатель.",
    "NotificationsGuidePermission": "Уведомления Parvane заблокированы в настройках системы.\n\nЧтобы включить:\n• Откройте настройки — Приложения — Parvane.\n• Уведомления — Разрешить уведомления.",
    "NotificationsGuideError": "**Parvane** не смог показать часть уведомлений этого аккаунта из-за неизвестной ошибки системы.\n\nПроверьте:\n• Установлены все обновления системы\n• Parvane обновлён\n• В настройках системы нет ограничений на уведомления.",
    "NotificationsGuideErrorChat": "**Parvane** не смог показать часть уведомлений от %1$s из-за неизвестной ошибки системы.\n\nПроверьте:\n• Установлены все обновления системы\n• Parvane обновлён\n• В настройках системы нет ограничений на уведомления.",
    "NotificationsGuideSyncGlobalOff": "Синхронизация данных выключена в настройках системы. Уведомления могут не приходить при закрытом приложении.\n\nЕё может неявно выключать режим экономии батареи.",
    "NotificationsGuideSyncAppOff": "Синхронизация данных выключена для Parvane. Уведомления могут не приходить при закрытом приложении.\n\nЕё может неявно выключать режим экономии батареи.",
    "NotificationSyncOffWarn": "**Нужны уведомления о новых сообщениях?**\n\nВключите системную автосинхронизацию, чтобы получать их при закрытом приложении.",
    "NotificationSyncDecline": "Нет, спасибо",
    "NotificationSyncAccept": "Включить",
    "TurnSyncOnSystem": "Включить синхронизацию",
    "TurnSyncOnApp": "Включить синхронизацию",
    "ForegroundSync": "Догружать пропущенные уведомления",
    "ForegroundSyncDesc": "Разрешить показывать **«Проверка новых сообщений»** в шторке, чтобы догрузить данные для уведомления.",
    "ForegroundSyncDescOn": "Иногда в шторке будет **«Проверка новых сообщений»** при закрытом приложении, пока уведомления не показаны.",
    "ForegroundSyncDescOff": "В шторке может появляться **«Возможно, новое сообщение»**, когда уведомление не удалось показать.",
    "PushServices": "Push-службы",
    "ShareNotificationError": "Отправить отчёт об ошибке",
    "NotificationsModeAllHint": "Уведомления со всех аккаунтов.",
    "NotificationsModeActiveHint": "Уведомления только с текущего аккаунта.",
    "NotificationsModeActive": "Текущий аккаунт",
    "NotificationsModeSelected": "Выбранные аккаунты",
    "NotificationsModeSelectedHint_one": "Уведомления только с %1$s выбранного аккаунта.", "NotificationsModeSelectedHint_other": "Уведомления только с выбранных аккаунтов (%1$s).",
    "NotificationsModeSelectedMore_one": "Показать ещё %1$s аккаунт", "NotificationsModeSelectedMore_other": "Показать ещё аккаунты (%1$s)",
    "NotificationsModeSelectedMoreMuted_one": "Показать %1$s аккаунт без звука", "NotificationsModeSelectedMoreMuted_other": "Показать аккаунты без звука (%1$s)",
    "TooManySelectedAccounts": "Хотя бы один аккаунт должен остаться выбранным.",
    "NotificationsEnableOverride2": "Включение уведомлений для этих чатов переопределит общее значение из «Настройки → Уведомления» (%1$s).",
    "NotificationsEnableOverride3": "Включение уведомлений для части выбранных чатов переопределит общее значение из «Настройки → Уведомления» (%1$s).",
    # ── настройки: данные и память ──
    "StorageUsage": "Использование памяти",
    "StorageUsageHint": "Управление местом на диске",
    "NetworkUsage": "Использование сети",
    "MobileUsage": "Мобильный трафик",
    "WiFiUsage": "Трафик Wi-Fi",
    "RoamingUsage": "Трафик в роуминге",
    "ResetStatistics": "Сбросить статистику",
    "ResetStatsHint": "Сбросить статистику использования сети?",
    "DeleteChatCache": "Очистить кэш медиа",
    "DataSaver": "Экономия трафика",
    "DataSaverDesc": "При экономии трафика медиа не скачивается автоматически. Текущие загрузки приостановлены.",
    "SizeUnit": "Единицы размера",
    "SizeUnitMetric": "1000 байт = 1 КБ, 1000 КБ = 1 МБ",
    "SizeUnitBinary": "1024 байта = 1 КиБ, 1024 КиБ = 1 МиБ",
    "OnMobileNetwork": "В мобильной сети",
    "OnRoaming": "В роуминге",
    "WhenUsingMobileData": "При переходе на мобильные данные",
    "WhenUsingRoaming": "При переходе в роуминг",
    "WhenUsingMobileDataOrRoaming": "При переходе на мобильные данные или в роуминг",
    "RestrictOverMobile": "Ограничить в мобильной сети",
    "RestrictOnWiFi": "Ограничить в Wi-Fi",
    "RestrictOnRoaming": "Ограничить в роуминге",
    "UseLessDataAlways": "Всегда",
    "VoipUseLessData": "Меньше трафика для звонков",
    "UseLessDataForCallsDesc": "Экономия трафика улучшает связь в плохих сетях, но немного снижает качество звука.",
    "VoiceCalls": "Голосовые звонки",
    "ConfirmCalls": "Подтверждать звонок",
    "ConfirmCallsDesc": "Спрашивать подтверждение перед каждым звонком.",
    "AutoplayGifs": "Автовоспроизведение GIF",
    "SaveOutgoingPhotos": "Сохранять отредактированные фото в галерею",
    "CompressAudio": "Сжимать звук в видео",
    "ForceBuiltinDecoding": "Принудительно встроенное декодирование",
    "DisableHlsVideo": "Отключить HLS-видео",
    "UseInAppBrowser": "Встроенный браузер",
    "OpenEmbed": "Предпросмотр внешних ссылок",
    "OpenEmbedDesc": "Показывать встроенный предпросмотр при открытии поддерживаемых ссылок",
    "AutoInstantView": "Открывать в Instant View",
    "AutoInstantViewDesc": "При открытии ссылки Parvane попробует показать её в Instant View.",
    "AutoInstantViewNone": "Никакие ссылки",
    "AutoInstantViewAll": "Все ссылки",
    "IgnoreRestrictions": "Игнорировать ограничения контента",
    "DisplaySensitiveContent": "Показывать чувствительный контент",
    "EarpieceMode": "Воспроизведение через динамик у уха",
    "EarpieceModeProximity": "Когда телефон у уха",
    "EarpieceModeAlways": "Всегда",
    "UseHqRoundVideos": "Кружки в высоком качестве",
    "UseRearRoundVideos": "Начинать с задней камеры",
    "Camera": "Встроенная камера",
    "CameraSettings": "Настройки камеры",
    "CameraType": "Тип камеры",
    "CameraTypeLegacy": "Классическая",
    "CameraTypeXBeta": "CameraX (экспериментально)",
    "CameraUseSystem": "Системная камера",
    "CameraRatio": "Соотношение сторон",
    "CameraRatioFull": "На весь экран",
    "CameraGrid": "Сетка",
    "CameraFlip": "Как в предпросмотре",
    "CameraFlipInfo": "Сохранять селфи как в предпросмотре, без зеркального отражения.",
    "CameraKeepMedia": "Хранить отменённые снимки",
    "CameraVolume": "Кнопка громкости",
    "CameraVolumeShoot": "Снимок или запись видео",
    "CameraVolumeZoom": "Зум",
    "CameraVolumeNone": "Системная громкость",
    "TakePhotoError": "Ошибка при съёмке",
    "TakeVideoError": "Ошибка при записи видео",
    # ── язык ──
    "MoreLanguages": "Другие языки",
    "LanguageSectionInstalled": "Установленные",
    "LanguageDelete": "Удалить язык",
    "RemoveLanguage": "Удалить локализацию",
    "LocalizationView": "Просмотр строк",
    "LocalizationCreateTitle": "Создать локализацию",
    "LocalizationEdit": "Редактировать локализацию",
    "LocalisationShare": "Поделиться как XML",
    "LocalisationApplied": "Локализация применена",
    "LanguageEmpty": "Файл локализации пуст",
    "InvalidLocalisation": "Некорректный файл локализации",
    "LanguageDeleteConfirm": "Удалить этот язык?\n\n%1$s / %2$s исчезнет из списка языков.\n\nВернуть можно по ссылке:\n%3$s",
    "DeleteLanguageConfirm": "Удалить этот файл локализации?\n\n%1$s / %2$s исчезнет из списка установленных языков.",
    "language_appliedLanguage": "Язык приложения: русский.",
    "language_continueInLanguagePopupText": "**Parvane** доступен на **русском**.\n\nПереключить язык приложения?\n\nИзменить можно в «Настройки → Язык».",
    # ── обновления, о приложении ──
    "AppUpdates": "Обновления приложения",
    "InAppUpdates": "Обновления в приложении",
    "AutoUpdateWiFi": "По Wi-Fi",
    "AutoUpdatePrompt": "Спрашивать",
    "AutoUpdateAlways": "Всегда",
    "InstallUpdate": "Установить обновление",
    "DownloadUpdate": "Скачать обновление",
    "DownloadUpdateSize": "Скачать обновление (%1$s)",
    "AppUpdateReady": "Parvane готов к обновлению.",
    "AppOnGooglePlay": "Приложение в Google Play",
    "AppLogs": "Логи приложения",
    "TdlibLogs": "Логи ядра",
    "CopyReportData": "Скопировать данные отчёта",
    "CopyReportDataInfo": "Для отправки отчёта об ошибке",
    "SubscribeToBeta": "Бета-обновления",
    "OpenSourceGuide": "**Parvane** — открытый проект. Исходный код установленной версии доступен для просмотра.",
    "AppSignature": "**Parvane** `%1$s`",
    "format_commit": "%1$s (коммит %2$s)",
    "CommitInfo": "коммит %1$s, %2$s",
    "ViewSourceCodeChangesSince": "С %1$s (коммит %2$s)",
    "PullRequestCommit": "Pull Request #%1$d",
    "PR": "PR #%1$d",
    "xPRs_one": "%1$s PR", "xPRs_other": "PR: %1$s",
    "PullRequestsInfo_one": "Сборка включает %1$s pull request на рассмотрении", "PullRequestsInfo_other": "Сборка включает pull request'ы на рассмотрении: %1$s",
    "format_PRMadeBy": "%1$s от %2$s",
    "format_nameAndStatus": "%1$s\n%2$s",
    "format_languageStatus": "%1$s (%2$d%%)",
    "format_activeAndRevokedLinks": "%1$s, %2$s",
    "format_signedInAppsOnDevices": "%1$s %2$s",
    # ── сессии ──
    "SignedInNoOtherSessions": "Других сессий нет",
    "SignedInOtherDevice": "Вы также вошли на %1$s",
    "SignedInOtherSession": "Вы также вошли в %1$s",
    "SignedInXOtherDevices_one": "Вы вошли ещё на %1$s устройстве", "SignedInXOtherDevices_other": "Вы вошли ещё на устройствах: %1$s",
    "SignedInXOtherApps_one": "Вы вошли ещё в %1$s приложении", "SignedInXOtherApps_other": "Вы вошли ещё в приложениях: %1$s",
    "part_SignedInXOtherDevices_one": "ещё на %1$s устройстве", "part_SignedInXOtherDevices_other": "ещё на устройствах: %1$s",
    "part_SignedInXOtherApps_one": "Вы вошли ещё в %1$s приложении", "part_SignedInXOtherApps_other": "Вы вошли ещё в приложениях: %1$s",
    "part_SignedInXDevices_one": "на %1$s устройстве", "part_SignedInXDevices_other": "на устройствах: %1$s",
    "part_SignedInXApps_one": "Вы вошли в %1$s приложении", "part_SignedInXApps_other": "Вы вошли в приложениях: %1$s",
    "XSignInAttempts_one": "У вас %1$s незавершённая попытка входа", "XSignInAttempts_other": "Незавершённых попыток входа: %1$s",
    # ── напоминания профиля ──
    "ReminderSetBirthdate": "Расскажите, когда у вас праздник",
    "ReminderSetBirthdateText": "Добавьте день рождения",
    "ReminderSetLoginEmail": "Задайте e-mail для входа",
    "ReminderSetLoginEmailText": "Чтобы всегда получать коды входа",
    "ReminderCheckPhoneNumber": "Проверьте номер телефона",
    "ReminderCheckPhoneNumberText": "%1$s — всё ещё ваш номер?",
    "ReminderCheckPhoneNumberHide": "Оставить %1$s",
    "ReminderCheckPhoneNumberDescription": "Держите номер актуальным, чтобы всегда иметь доступ к Parvane.",
    "ReminderCheckTfaPassword": "Проверьте пароль",
    "ReminderCheckTfaPasswordHide": "Скрыть подсказку",
    "ReminderCheckTfaPasswordDescription": "Проверьте, что помните пароль двухэтапной проверки, чтобы всегда иметь доступ к Parvane.",
    "ReminderActionVerifyPassword": "Проверить пароль",
    "ReminderActionChangePhoneNumber": "Сменить номер",
    "NumberHiddenHint": "Номер станет виден, когда %1$s добавит вас в контакты или изменит настройки приватности.",
    # ── медиа-редактор, эмодзи ──
    "EmojiSetUpdated": "Набор эмодзи %1$s обновлён. Скачать новую версию?",
    "EmojiSetUpdate": "Скачать и обновить",
    "SendDiceAsEmoji": "Отправить как эмодзи",
    "OpenSupergroup": "Открыть супергруппу",
    "OpenCloudChat": "Открыть облачный чат",
    "UpgradeChatPrompt": "Для этого действия чат будет преобразован в супергруппу.\n\n**Внимание**: новые участники не увидят сообщения до преобразования.",
    "AgeVerification_one": "Использовать Parvane можно с %1$s года.", "AgeVerification_other": "Использовать Parvane можно с %1$s лет.",
    "CategoryArchiveUnread": "Архив / Непрочитанные",
    "CategoryArchivePrivate": "Архив / Личные",
    "CategoryArchiveGroup": "Архив / Группы",
}
