// Синтез ApiOldLangPack для старого lang-провайдера (useOldLang). Без него
// легаси-экраны показывают голые ключи вида `Weekday.ShortMonday`. Имена
// дней/месяцев берём из Intl — без сети. Ключи, которых здесь нет, старый
// провайдер добирает из нового пакета (fallback.strings / ru.strings), см.
// util/oldLangProvider.ts.

import type { ApiOldLangPack } from '../types';

const WEEKDAY_KEYS = [
  'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
];

const MONTH_KEYS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export const OLD_LANG_PACK_EN: ApiOldLangPack = {
  Cancel: 'Cancel',
  DialogPin: 'Pin',
  StopLiveLocation: 'Stop Sharing Location',
  AttachLiveLocation: 'Live Location',
  'LiveLocationUpdated.JustNow': 'updated just now',
  'LiveLocationUpdated.MinutesAgo': { oneValue: 'updated %@ minute ago', otherValue: 'updated %@ minutes ago' },
  'LiveLocationUpdated.TodayAt': 'updated at %@',
  DialogUnpin: 'Unpin',
  Forward: 'Forward',
  PinMessageAlertChat: 'Do you want to pin this message for both participants?',
  PinMessageAlertTitle: 'Pin Message',
  UnreadMessages: 'Unread Messages',
  'Conversation.PinMessagesFor': 'Also pin for %@',
  'Weekday.Today': 'Today',
  'Weekday.Yesterday': 'Yesterday',
  formatDateAtTime: '%1$s at %2$s',
  'Time.TodayAt': 'today at %@',
  'Time.YesterdayAt': 'yesterday at %@',
  'Time.AtDate': '%@',
  'Time.JustNow': 'just now',
  'Time.MinutesAgo': { oneValue: '%@ minute ago', otherValue: '%@ minutes ago' },
  'StickerPack.AddStickerCount': { oneValue: 'Add %@ Sticker', otherValue: 'Add %@ Stickers' },
  'StickerPack.RemoveStickerCount': { oneValue: 'Remove %@ Sticker', otherValue: 'Remove %@ Stickers' },
  SETTINGS: 'Settings',
  lng_settings_information: 'Edit profile',
  FirstName: 'First name (required)',
  LastName: 'Last name (optional)',
  UserBio: 'Bio (optional)',
  Save: 'Save',
  Username: 'Username',
  UsernameHelp: 'Usernames are not supported on this server yet.',
  lng_settings_about_bio: 'Any details such as age, occupation or city.',
  LogOutTitle: 'Log Out',
  'Common.Select': 'Select',
  'Chat.ForwardActionHeader': 'Forward',
  'AttachmentMenu.PhotoOrVideo': 'Photo or Video',
  AttachDocument: 'Document',
  lng_context_remove_from_group: 'Remove from group',
  'GroupRemoved.Remove': 'Remove user',
  'PeerInfo.Confirm.RemovePeer': 'Remove %@ from the group?',
  lng_box_remove: 'Remove',
  lng_channel_add_users: 'Add members',
  Online: 'online',
  Lately: 'last seen recently',
  'LastSeen.JustNow': 'last seen just now',
  'LastSeen.MinutesAgo': { oneValue: 'last seen %@ minute ago', otherValue: 'last seen %@ minutes ago' },
  'LastSeen.HoursAgo': { oneValue: 'last seen %@ hour ago', otherValue: 'last seen %@ hours ago' },
  'LastSeen.TodayAt': 'last seen today at %@',
  'LastSeen.YesterdayAt': 'last seen yesterday at %@',
  'LastSeen.AtDate': 'last seen %@',
  ScheduleMessage: 'Schedule Message',
  SendWithoutSound: 'Send Without Sound',
  'Conversation.ScheduleMessage.SendToday': 'Send today at %@',
  'Conversation.ScheduleMessage.SendOn': 'Send on %@ at %@',
  BlockedUsers: 'Blocked Users',
  SendMessage: 'Send Message',
  NewMessageTitle: 'New Message',
  GroupAddMembers: 'Add Members',
  Emoji: 'Emoji',
  AccDescrStickers: 'Stickers',
  AccDescrVoiceMessage: 'Record voice message',
  AccDescrVideoMessage: 'Record video message',
  AttachAudio: 'Voice Message',
  SharedMedia: 'Shared Media',
  SavedMessages: 'Saved Messages',
  CallMessageIncoming: 'Incoming Call',
  CallMessageOutgoing: 'Outgoing Call',
  CallMessageIncomingMissed: 'Missed Call',
  CallMessageOutgoingMissed: 'Canceled Call',
  CallMessageIncomingDeclined: 'Declined Call',
  CallMessageVideoIncoming: 'Incoming Video Call',
  CallMessageVideoOutgoing: 'Outgoing Video Call',
  CallMessageVideoIncomingMissed: 'Missed Video Call',
  CallMessageVideoOutgoingMissed: 'Canceled Video Call',
  CallMessageVideoIncomingDeclined: 'Declined Video Call',
  CallMessageWithDuration: '%1$@ (%2$@)',
  CallAgain: 'Call Again',
  CallBack: 'Call Back',
  VideoCall: 'Video Call',
  ParvaneGroupCall: 'Group Call',
  ChannelAdministrators: 'Administrators',
  ChannelCreator: 'Owner',
  ChannelAdmin: 'Admin',
  'Channel.Management.AddModerator': 'Add Admin',
  EditAdminPromotedBy: 'Promoted by',
  GroupMembers: 'Members',
  ChannelSubscribers: 'Subscribers',
  ChannelBlockedUsers: 'Removed users',
  ChannelPermissions: 'Permissions',
  GroupType: 'Group Type',
  ChannelType: 'Channel Type',
  Loading: 'Loading...',
  Search: 'Search',
  DeleteMega: 'Delete Group',
  DeleteGroupForAll: 'Delete for all members',
  DeleteForAll: 'Delete for everyone',
  ChannelDelete: 'Delete Channel',
  ChannelDeleteAlert: 'Wait! Deleting this channel will remove all subscribers '
    + 'and all messages will be lost. Delete the channel anyway?',
  ChannelLeaveAlert: 'Are you sure you want to leave this channel?',
  ChannelLeaveAlertWithName: 'Are you sure you want to leave %@?',
  LeaveChannel: 'Leave Channel',
  'Group.LeaveGroup': 'Leave Group',
  'ChannelIntro.CreateChannel': 'Create Channel',
  SendMessageTo: 'Send message to...',
  'Channel.LeaveChannel': 'Leave Channel',
  AreYouSureDeleteAndExit: 'Are you sure you want to delete and leave the group?',
  'ChatList.DeleteAndLeaveGroupConfirmation': 'Are you sure you want to leave and delete %@?',
  'ChatList.DeleteChatConfirmation': 'Are you sure you want to delete %@?',
  DeleteChatUser: 'Delete chat',
  'ChatList.DeleteForCurrentUser': 'Delete just for me',
  'ChatList.DeleteForEveryone': 'Delete for me and %@',
  DeleteAndStop: 'Delete and stop',
  ParvaneCallBusy: 'Line busy',
  ParvaneCallMute: 'Mute',
  ParvaneCallUnmute: 'Unmute',
  ParvaneCallCameraOff: 'Turn camera off',
  ParvaneCallCameraOn: 'Turn camera on',
  GifsTab: 'GIFs',
  'StickersList.EmojiItem': 'Custom Emoji',
  Call: 'Call',
  CallAccept: 'Accept',
  CallEndCall: 'End Call',
  CallStatusRequesting: 'requesting...',
  CallStatusRinging: 'ringing...',
  CallStatusIncoming: 'is calling you...',
  CallStatusExchanging: 'exchanging encryption keys...',
  ParvaneCallSecurityError: 'Call security check failed',
  CallEmojiKeyTooltip: 'If these emoji match what %@ sees, this call is fully secure',
  lng_polls_stop: 'Stop poll',
  lng_polls_stop_warning: 'If you stop this poll now, nobody will be able to vote in it anymore',
  lng_polls_stop_sure: 'Stop poll',
  GroupName: 'Group name',
  EnterChannelName: 'Channel name',
  'GroupInfo.ParticipantCount': { oneValue: '%@ member', otherValue: '%@ members' },
  lng_info_user_title: 'User Info',
  lng_info_group_title: 'Group Info',
  'GroupInfo.Title': 'Group Info',
  BlockedUsersInfo: 'Blocked users cannot send you messages',
  NoBlocked: 'No blocked users yet',
  BlockContact: 'Block',
  Unblock: 'Unblock',
  'SharedMedia.EmptyTitle': 'No shared media yet',
  NewGroup: 'New Group',
  // Разделитель в авто-имени группы из участников («Alice & Bob»); без ключа
  // сырой текст попадал в НАЗВАНИЕ создаваемой группы
  'CreateGroup.PeersTitleLastDelimeter': ' & ',
  NewChannel: 'New Channel',
  StickersName: 'Stickers and Emoji',
  SuggestStickers: 'Sticker suggestions by emoji',
  'InstalledStickers.DynamicPackOrder': 'Dynamic pack order',
  'InstalledStickers.DynamicPackOrderInfo': 'Frequently used sticker packs move up automatically',
  ChooseStickerMyStickerSets: 'My sticker sets',
  StickersBotInfo: 'Create your own packs in Settings',
  DoubleTapSetting: 'Quick reaction',
  ChatsMute: 'Mute',
  ChatsUnmute: 'Unmute',
  ReportSelectMessages: 'Select Messages',
  ParvaneAutoDelete: 'Auto-Delete',
  ParvaneAutoDeleteOff: 'Off',
  ParvaneAutoDelete1h: '1 hour',
  ParvaneAutoDelete1d: '1 day',
  ParvaneAutoDelete1w: '1 week',
  'ChatList.Mute': 'Mute',
  'ChatList.Unmute': 'Unmute',
  lng_context_copy_image: 'Copy Image',
  lng_context_copy_text: 'Copy Text',
  lng_context_copy_selected: 'Copy Selected Text',
  lng_context_copy_link: 'Copy Link',
  lng_media_download: 'Download',
  lng_context_cancel_download: 'Cancel Download',
  lng_context_save_gif: 'Save GIF',
  lng_polls_retract: 'Retract Vote',
  Delete: 'Delete',
  Edit: 'Edit',
  MessageScheduleSend: 'Send Now',
  MessageScheduleEditTime: 'Reschedule',
  'MuteFor.Hours': { oneValue: 'Mute for %@ hour', otherValue: 'Mute for %@ hours' },
  'MuteFor.Days': { oneValue: 'Mute for %@ day', otherValue: 'Mute for %@ days' },
  'MuteFor.Forever': 'Mute forever',
  'Common.Done': 'Done',
  ParvaneCreatePack: 'Create Sticker Pack',
  ParvaneExportKeys: 'Export E2E Keys',
  ParvaneImportKeys: 'Import E2E Keys',
  // Заголовок экрана Settings → Devices (SettingsHeader)
  SessionsTitle: 'Devices',
  // Авто-линковка истории (Settings → Devices)
  ParvaneLinkPendingTitle: 'History transfer',
  ParvaneLinkPendingText: 'Waiting for your other device. Open Settings → Devices there and confirm code %@.',
  ParvaneLinkRequests: 'History transfer requests',
  ParvaneLinkOfferCode: 'Code: %@',
  ParvaneLinkConfirm: 'Transfer message history to this device? Make sure it shows code %@.',
  ParvaneLinkConfirmAction: 'Transfer',
  ParvaneLinkGranted: 'History transferred',
  ParvaneLinkFailed: 'History transfer failed',
  ParvaneKeysPasswordPrompt: 'Backup password',
  ParvaneKeysExported: 'E2E keys exported',
  ParvaneKeysExportFailed: 'Could not export E2E keys',
  ParvaneKeysImported: 'E2E keys imported, resyncing history',
  ParvaneKeysImportFailed: 'Could not import E2E keys',
  ParvanePackNamePrompt: 'Sticker pack name',
  ParvanePackCreated: 'Sticker pack created: %@',
  ParvanePackCreateFailed: 'Could not create sticker pack',
  FilterNoChatsToDisplay: 'No chats yet',
  'Chat.EmptyChat': 'Start messaging by searching for a contact',
  'ChatList.EmptyChatListFilterText': 'No chats currently match this folder',
  'ChatList.EmptyChatListEditFilter': 'Edit Folder',
  NoMessages: 'No messages here yet...',
  'Conversation.EmptyPlaceholder': 'No messages here yet...',
  'Conversation.GreetingText': 'Send a message to start the conversation',
  Close: 'Close',
  lng_sure_logout: 'Are you sure you want to log out?',
  'AccountSettings.Logout': 'Log Out',
  AccDescrGoBack: 'Go back',

  // ── Язык ────────────────────────────────────────────────────────────────
  Language: 'Language',
  'Localization.InterfaceLanguage': 'Interface Language',

  // ── Папки ───────────────────────────────────────────────────────────────
  FilterEdit: 'Edit Folder',
  FilterChatTypes: 'Chat types',
  'ChatList.PeerTypeContact': 'contact',
  'ChatList.PeerTypeNonContactUser': 'user',
  'ChatList.PeerTypeBot': 'bot',
  FilterShowMoreChats: { oneValue: 'Show %@ more chat', otherValue: 'Show %@ more chats' },

  // ── Удаление сообщений / чата ───────────────────────────────────────────
  'Chat.DeleteMessagesConfirmation': {
    oneValue: 'Are you sure you want to delete this message?',
    otherValue: 'Are you sure you want to delete these messages?',
  },
  'Conversation.DeleteMessagesForEveryone': 'Delete for everyone',
  DeleteProceedBtn: 'Delete',
  DeleteMessagesOptionAlso: 'Also delete for %@',
  DeleteAdditionalActions: 'Additional actions',
  DeleteAllFrom: 'Delete all from %@',
  DeleteAllFromUsers: 'Delete all from these users',
  DeleteBan: 'Ban %@',
  DeleteBanUsers: 'Ban these users',
  DeleteRestrictUsers: 'Restrict these users',
  KickFromSupergroup: 'Remove from group',
  ReportSpamTitle: 'Report spam',
  UserRestrictionsCanDoUsers: { oneValue: 'What can this user do?', otherValue: 'What can these users do?' },
  lng_delete_for_everyone_hint: {
    oneValue: 'This will delete it for everyone in this chat.',
    otherValue: 'This will delete them for everyone in this chat.',
  },
  lng_delete_for_me_chat_hint: {
    oneValue: 'This will delete it just for you, not for other participants of the chat.',
    otherValue: 'This will delete them just for you, not for other participants of the chat.',
  },
  ClearHistoryMessageSingle: 'Are you sure you want to clear the history with %@?',
  ClearHistoryMyNotesMessage: 'Are you sure you want to clear your notes?',

  // ── Шапка чата, меню, поиск ─────────────────────────────────────────────
  BlockUser: 'Block user',
  'GroupInfo.DeleteAndExit': 'Delete and leave',
  'Common.Back': 'Back',
  'Common.Close': 'Close',
  'Channel.TitleInfo': 'Channel Info',
  'Group.Info.AdminLog': 'Recent Actions',
  lng_group_invite_title: 'Invite Links',
  'Conversation.SearchPlaceholder': 'Search',
  Hide: 'Hide',
  MarkAllAsRead: 'Mark all as read',
  SavedOpenChat: 'Open chat',
  'Chat.Pinned.UnpinAll': { oneValue: 'Unpin %@ message', otherValue: 'Unpin all %@ messages' },
  'Chat.PanelUnpinAllMessages': 'Unpin all messages',
  'Chat.UnpinAllMessagesConfirmation': {
    oneValue: 'Do you want to unpin %@ message in this chat?',
    otherValue: 'Do you want to unpin all %@ messages in this chat?',
  },
  'Conversation.PinMessageAlert.PinAndNotifyMembers': 'Notify all members',
  'Share.Link.Copied': 'Link copied to clipboard',
  lng_context_copy_selected_items: 'Copy selected as text',
  'Conversation.ReportMessages': 'Report',
  ForwardedFrom: 'Forwarded from',
  lng_context_forward_msg: 'Forward Message',
  ReplyToQuote: 'Reply to %@',
  DoNotReply: 'Do not reply',
  EditMessage: 'Edit message',
  ForwardAnotherChat: 'Forward to another chat',
  ForwardedMessageCount: { oneValue: '%@ forwarded message', otherValue: '%@ forwarded messages' },
  'Message.Context.Goto': 'Show message',
  RemoveQuote: 'Remove quote',
  ReplyToAnotherChat: 'Reply in another chat',
  SendWhenOnline: 'Send when online',
  'Schedule.SendWhenOnline': 'Send When Online',
  'Chat.PlayOnceVoiceMessageTooltip': 'Send the message once',
  FilterByUser: 'Filter by user',
  NoResult: 'No results',
  NoResultFoundFor: 'No results for "%@"',
  Of: '%1$d of %2$d',
  SearchAsChat: 'Show as chat',
  SearchAsList: 'Show as list',
  SearchMyMessages: 'Search my messages',
  SearchThisChat: 'Search this chat',
  HashtagSearchPlaceholder: 'Search hashtags',
  SearchHashtagsHint: 'Search for hashtags across messages',
  'ChatList.Search.NoResults': 'No Results',
  'ChatList.Search.NoResultsDescription': 'There were no results.\nTry a new search.',
  'Conversation.ContextViewReplies': { oneValue: 'View %@ Reply', otherValue: 'View %@ Replies' },
  MessageContainsEmojiPack: 'This message contains emoji from the **%@** pack.',
  MessageContainsEmojiPacks: {
    oneValue: 'This message contains emoji from %@ pack.',
    otherValue: 'This message contains emoji from %@ packs.',
  },
  PmRead: 'Read',
  PmReadAt: 'Read %@',
  PmReadShowWhen: 'Show read time',
  'Chat.PrivateMessageEditTimestamp.Date': 'Edited %@',
  'Chat.EmptyStateIntroFooter': 'Send a message to %@ to start the conversation',
  'ScheduledMessages.EmptyPlaceholder': 'No scheduled messages here yet...',
  'EmptyGroupInfo.Title': 'You have created a group',
  'EmptyGroupInfo.Subtitle': 'Groups can have:',
  'EmptyGroupInfo.Line1': 'Up to 200,000 members',
  'EmptyGroupInfo.Line2': 'Persistent chat history',
  'EmptyGroupInfo.Line3': 'Invite links',
  'EmptyGroupInfo.Line4': 'Admins with different rights',
  'Conversation.CloudStorageInfo.Title': 'Your cloud storage',
  'Conversation.ClousStorageInfo.Description1': 'Forward messages here to save them.',
  'Conversation.ClousStorageInfo.Description2': 'Send media and files to store them.',
  'Conversation.ClousStorageInfo.Description3': 'Access this chat from any device.',
  'Conversation.ClousStorageInfo.Description4': 'Use search to quickly find things.',

  // ── Профиль, контакты, участники ────────────────────────────────────────
  Members: { oneValue: '%@ member', otherValue: '%@ members' },
  StatusHiddenShow: 'Show',
  UsernameAlso: 'Also %USERNAMES%',
  SavedMessagesTab: 'Saved Messages',
  lng_media_audio_empty: 'No voice messages',
  lng_media_file_empty: 'No files',
  lng_media_gif_empty: 'No GIFs',
  lng_media_link_empty: 'No links',
  lng_media_song_empty: 'No music',
  lng_new_contact_add: 'Add contact',
  lng_new_contact_block: 'Block',
  'UserInfo.BlockConfirmationTitle': 'Block %@?',
  SharedContactAdd: 'Add contact',
  SharedContactMessage: 'Message',
  PhoneCopied: 'Phone copied to clipboard',
  'UserInfo.FirstNamePlaceholder': 'First name',
  'UserInfo.LastNamePlaceholder': 'Last name',
  Reset: 'Reset',
  Checking: 'Checking...',
  UsernameCopied: 'Username copied to clipboard',
  'ProfilePhoto.SetMainPhoto': 'Set as main photo',
  Confirm: 'Confirm',
  AreYouSure: 'Are you sure?',
  'Preview.DeletePhoto': 'Delete photo',
  ChannelHideMembers: 'Hide members',
  'Channel.EditAdmin.Permission.BanUsers': 'Ban users',
  ChatHistoryHiddenInfo2: 'New members won\'t see earlier messages.',
  ChatHistoryVisibleInfo: 'New members will see messages that were sent before they joined.',
  'GroupInfo.InviteLinks': 'Invite Links',
  ReactionsAll: 'All',
  ReactionsOff: 'Off',
  'Channel.DiscussionGroup.LinkGroup': 'Link Group',
  ChannelSignMessagesWithProfile: 'Show authors\' profiles',
  ChannelSignProfilesInfo: 'Add names of the admins to the messages they post.',
  'InviteLink.InviteLink': 'Invite link',
  'InviteLink.Expired': 'Expired',
  'InviteLink.ExpiresIn': 'expires in %@',
  lng_create_permanent_link_title: 'Primary link',
  lng_group_invite_expire_custom: 'Custom',
  lng_group_invite_usage_custom: 'Custom',
  'ChannelVisibility.Forwarding.Enabled': 'Members can forward messages from this group and save media.',
  'ChannelVisibility.Forwarding.Disabled': 'Members can\'t forward messages from this group or save media.',
  'ChannelVisibility.Forwarding.GroupInfo': 'Restrict Saving Content',
  'ChannelVisibility.Forwarding.ChannelInfo': 'Restrict Saving Content',
  AllReactions: 'All Reactions',
  SomeReactions: 'Some Reactions',
  NoReactions: 'No Reactions',
  AvailableReactions: 'Available reactions',
  OnlyAllowThisReactions: 'Only allow these reactions',
  EnableAllReactionsInfo: 'Members of the group can use any emoji as reactions to messages.',
  EnableSomeReactionsInfo: 'You can select emoji that will allow members of the group to react to messages.',
  DisableReactionsInfo: 'Members of the group can\'t react to messages.',
  MaximumReactionsHeader: 'Maximum reactions per post',
  'ChannelReactions.MaxCount.Info': 'Limit the number of different reactions that can be added to a message.',
  'PeerInfo.AllowedReactions.MaxCountValue': '%@',

  // ── Стикеры, вложения, медиа ────────────────────────────────────────────
  'Stickers.AddToFavorites': 'Add to Favorites',
  'Stickers.RemoveFromFavorites': 'Remove from Favorites',
  StickersCopy: 'Copy Link',
  'StickerPack.StickerCount': { oneValue: '%@ sticker', otherValue: '%@ stickers' },
  SuggestAnimatedEmoji: 'Suggest emoji',
  EmojiBotInfo: 'Custom emoji come from installed sticker packs.',
  lng_launch_exe_dont_ask: 'Don\'t ask again',
  lng_launch_svg_warning: 'This file may contain code that runs in the browser. Open anyway?',
  'Video.Unsupported.Desktop': 'This video is not supported by your browser.',
  'Video.Unsupported.Mobile': 'This video is not supported by your browser.',
  i18n_dragToSort: 'Drag to sort',
  lng_context_archive_to_list: 'Move to main list',
  SearchEmptyViewTitle: 'No results',

  // ── Звонки ──────────────────────────────────────────────────────────────
  lng_call_accept: 'Accept',
  lng_call_screencast: 'Share screen',
  lng_call_status_requesting: 'Connecting...',
  lng_call_status_ringing: 'Ringing...',
  lng_call_status_incoming: 'Incoming call',
  lng_call_status_waiting: 'Waiting...',
  lng_call_status_exchanging: 'Exchanging encryption keys...',
  lng_call_status_hanging: 'Ending call...',
  lng_call_rate_label: 'Rate the call',
  lng_call_rate_comment: 'What went wrong?',
  lng_group_call_leave: 'Leave',
  lng_group_call_settings: 'Settings',
  AccDescrCollapsePanel: 'Collapse panel',
  AccDescrExpandPanel: 'Expand panel',

  // ── Настройки ───────────────────────────────────────────────────────────
  Calls: 'Calls',
  'Privacy.ProfilePhoto': 'Profile Photos',
  PrivacyBio: 'Bio',
  lng_settings_experimental: 'Experimental',
  lng_settings_title_chat_name: 'Chat name in window title',
  lng_settings_window_system: 'Use system window frame',
  lng_username_link: 'Link',
  'ShortcutsController.Others.LockByPasscode': 'Lock',
  AnonymousForward: 'Anonymous',
  NewContact: 'New Contact',
  'Contacts.PhoneNumber.NotRegistred': 'There is no user with this nickname.',
  'UserInfo.NotificationsEnabled': 'Enabled',
  'UserInfo.NotificationsDisabled': 'Disabled',
  DeleteContact: 'Delete Contact',
  ParvaneTwoFactorTitle: 'Two-factor authentication',
  ParvaneTwoFactorToggle: 'Confirm sign-in in Telegram',
  ParvaneTwoFactorInfo: 'After the password, each new device must be confirmed in the Telegram account '
    + 'linked to this profile.',
  ParvaneTwoFactorNoTelegram: 'Link Telegram first: it is done when confirming the account via the bot.',
  ParvaneTwoFactorFailed: 'Could not change the two-factor setting',
};

export const OLD_LANG_PACK_RU: ApiOldLangPack = {
  Cancel: 'Отмена',
  DialogPin: 'Закрепить',
  StopLiveLocation: 'Остановить трансляцию',
  AttachLiveLocation: 'Трансляция геопозиции',
  'LiveLocationUpdated.JustNow': 'обновлено только что',
  'LiveLocationUpdated.MinutesAgo': {
    oneValue: 'обновлено %@ минуту назад',
    fewValue: 'обновлено %@ минуты назад',
    manyValue: 'обновлено %@ минут назад',
    otherValue: 'обновлено %@ минут назад',
  },
  'LiveLocationUpdated.TodayAt': 'обновлено в %@',
  DialogUnpin: 'Открепить',
  Forward: 'Переслать',
  PinMessageAlertChat: 'Закрепить это сообщение для обоих участников?',
  PinMessageAlertTitle: 'Закрепить сообщение',
  UnreadMessages: 'Непрочитанные сообщения',
  'Conversation.PinMessagesFor': 'Также закрепить для %@',
  'Weekday.Today': 'Сегодня',
  'Weekday.Yesterday': 'Вчера',
  formatDateAtTime: '%1$s в %2$s',
  'Time.TodayAt': 'сегодня в %@',
  'Time.YesterdayAt': 'вчера в %@',
  'Time.AtDate': '%@',
  'Time.JustNow': 'только что',
  'Time.MinutesAgo': {
    oneValue: '%@ минуту назад', fewValue: '%@ минуты назад', manyValue: '%@ минут назад', otherValue: '%@ минут назад',
  },
  'StickerPack.AddStickerCount': {
    oneValue: 'Добавить %@ стикер',
    fewValue: 'Добавить %@ стикера',
    manyValue: 'Добавить %@ стикеров',
    otherValue: 'Добавить %@ стикеров',
  },
  'StickerPack.RemoveStickerCount': {
    oneValue: 'Удалить %@ стикер',
    fewValue: 'Удалить %@ стикера',
    manyValue: 'Удалить %@ стикеров',
    otherValue: 'Удалить %@ стикеров',
  },
  SETTINGS: 'Настройки',
  lng_settings_information: 'Изменить профиль',
  FirstName: 'Имя (обязательно)',
  LastName: 'Фамилия (необязательно)',
  UserBio: 'О себе (необязательно)',
  Save: 'Сохранить',
  Username: 'Имя пользователя',
  UsernameHelp: 'Имена пользователей на этом сервере пока не поддерживаются.',
  lng_settings_about_bio: 'Например, возраст, род занятий или город.',
  LogOutTitle: 'Выйти',
  'Common.Select': 'Выбрать',
  'Chat.ForwardActionHeader': 'Переслать',
  'AttachmentMenu.PhotoOrVideo': 'Фото или видео',
  AttachDocument: 'Файл',
  lng_context_remove_from_group: 'Удалить из группы',
  'GroupRemoved.Remove': 'Удалить пользователя',
  'PeerInfo.Confirm.RemovePeer': 'Удалить %@ из группы?',
  lng_box_remove: 'Удалить',
  lng_channel_add_users: 'Добавить участников',
  Online: 'в сети',
  Lately: 'был(а) недавно',
  'LastSeen.JustNow': 'был(а) только что',
  'LastSeen.MinutesAgo': {
    oneValue: 'был(а) %@ минуту назад',
    fewValue: 'был(а) %@ минуты назад',
    manyValue: 'был(а) %@ минут назад',
    otherValue: 'был(а) %@ минут назад',
  },
  'LastSeen.HoursAgo': {
    oneValue: 'был(а) %@ час назад',
    fewValue: 'был(а) %@ часа назад',
    manyValue: 'был(а) %@ часов назад',
    otherValue: 'был(а) %@ часов назад',
  },
  'LastSeen.TodayAt': 'был(а) сегодня в %@',
  'LastSeen.YesterdayAt': 'был(а) вчера в %@',
  'LastSeen.AtDate': 'был(а) %@',
  ScheduleMessage: 'Запланировать сообщение',
  SendWithoutSound: 'Отправить без звука',
  'Conversation.ScheduleMessage.SendToday': 'Отправить сегодня в %@',
  'Conversation.ScheduleMessage.SendOn': 'Отправить %@ в %@',
  BlockedUsers: 'Заблокированные',
  SendMessage: 'Написать сообщение',
  NewMessageTitle: 'Новое сообщение',
  GroupAddMembers: 'Добавить участников',
  Emoji: 'Эмодзи',
  AccDescrStickers: 'Стикеры',
  AccDescrVoiceMessage: 'Записать голосовое сообщение',
  AccDescrVideoMessage: 'Записать видеосообщение',
  AttachAudio: 'Голосовое сообщение',
  SharedMedia: 'Общие медиа',
  SavedMessages: 'Избранное',
  CallMessageIncoming: 'Входящий звонок',
  CallMessageOutgoing: 'Исходящий звонок',
  CallMessageIncomingMissed: 'Пропущенный звонок',
  CallMessageOutgoingMissed: 'Отменённый звонок',
  CallMessageIncomingDeclined: 'Отклонённый звонок',
  CallMessageVideoIncoming: 'Входящий видеозвонок',
  CallMessageVideoOutgoing: 'Исходящий видеозвонок',
  CallMessageVideoIncomingMissed: 'Пропущенный видеозвонок',
  CallMessageVideoOutgoingMissed: 'Отменённый видеозвонок',
  CallMessageVideoIncomingDeclined: 'Отклонённый видеозвонок',
  CallMessageWithDuration: '%1$@ (%2$@)',
  CallAgain: 'Позвонить снова',
  CallBack: 'Перезвонить',
  VideoCall: 'Видеозвонок',
  ParvaneGroupCall: 'Групповой звонок',
  ChannelAdministrators: 'Администраторы',
  ChannelCreator: 'Владелец',
  ChannelAdmin: 'Администратор',
  'Channel.Management.AddModerator': 'Добавить администратора',
  EditAdminPromotedBy: 'Назначил(а)',
  GroupMembers: 'Участники',
  ChannelSubscribers: 'Подписчики',
  ChannelBlockedUsers: 'Удалённые пользователи',
  ChannelPermissions: 'Разрешения',
  GroupType: 'Тип группы',
  ChannelType: 'Тип канала',
  Loading: 'Загрузка...',
  Search: 'Поиск',
  DeleteMega: 'Удалить группу',
  DeleteGroupForAll: 'Удалить для всех участников',
  DeleteForAll: 'Удалить для всех',
  ChannelDelete: 'Удалить канал',
  ChannelDeleteAlert: 'Внимание! При удалении канала будут удалены все подписчики, '
    + 'а все сообщения будут потеряны. Всё равно удалить канал?',
  ChannelLeaveAlert: 'Вы действительно хотите покинуть этот канал?',
  ChannelLeaveAlertWithName: 'Вы действительно хотите покинуть %@?',
  LeaveChannel: 'Покинуть канал',
  'Group.LeaveGroup': 'Покинуть группу',
  'ChannelIntro.CreateChannel': 'Создать канал',
  SendMessageTo: 'Кому отправить...',
  'Channel.LeaveChannel': 'Покинуть канал',
  AreYouSureDeleteAndExit: 'Вы действительно хотите удалить группу и покинуть её?',
  'ChatList.DeleteAndLeaveGroupConfirmation': 'Вы действительно хотите покинуть и удалить %@?',
  'ChatList.DeleteChatConfirmation': 'Вы действительно хотите удалить %@?',
  DeleteChatUser: 'Удалить чат',
  'ChatList.DeleteForCurrentUser': 'Удалить только у меня',
  'ChatList.DeleteForEveryone': 'Удалить у меня и у %@',
  DeleteAndStop: 'Удалить и остановить',
  ParvaneCallBusy: 'Занято',
  ParvaneCallMute: 'Выключить микрофон',
  ParvaneCallUnmute: 'Включить микрофон',
  ParvaneCallCameraOff: 'Выключить камеру',
  ParvaneCallCameraOn: 'Включить камеру',
  GifsTab: 'GIF',
  'StickersList.EmojiItem': 'Свои эмодзи',
  Call: 'Позвонить',
  CallAccept: 'Принять',
  CallEndCall: 'Завершить',
  CallStatusRequesting: 'соединение...',
  CallStatusRinging: 'вызов...',
  CallStatusIncoming: 'звонит вам...',
  CallStatusExchanging: 'обмен ключами шифрования...',
  ParvaneCallSecurityError: 'Проверка безопасности звонка не пройдена',
  CallEmojiKeyTooltip: 'Если эти эмодзи совпадают с теми, что видит %@, звонок полностью защищён',
  lng_polls_stop: 'Завершить опрос',
  lng_polls_stop_warning: 'Если завершить опрос сейчас, никто больше не сможет в нём проголосовать',
  lng_polls_stop_sure: 'Завершить опрос',
  GroupName: 'Название группы',
  EnterChannelName: 'Название канала',
  'GroupInfo.ParticipantCount': {
    oneValue: '%@ участник', fewValue: '%@ участника', manyValue: '%@ участников', otherValue: '%@ участников',
  },
  lng_info_user_title: 'Информация',
  lng_info_group_title: 'О группе',
  'GroupInfo.Title': 'О группе',
  BlockedUsersInfo: 'Заблокированные пользователи не могут писать вам',
  NoBlocked: 'Заблокированных пользователей нет',
  BlockContact: 'Заблокировать',
  Unblock: 'Разблокировать',
  'SharedMedia.EmptyTitle': 'Общих медиа пока нет',
  NewGroup: 'Новая группа',
  'CreateGroup.PeersTitleLastDelimeter': ' и ',
  NewChannel: 'Новый канал',
  StickersName: 'Стикеры и эмодзи',
  SuggestStickers: 'Подсказывать стикеры по эмодзи',
  'InstalledStickers.DynamicPackOrder': 'Динамический порядок наборов',
  'InstalledStickers.DynamicPackOrderInfo': 'Часто используемые наборы стикеров поднимаются вверх',
  ChooseStickerMyStickerSets: 'Мои наборы стикеров',
  StickersBotInfo: 'Создавайте свои наборы в настройках',
  DoubleTapSetting: 'Быстрая реакция',
  ChatsMute: 'Выключить уведомления',
  ChatsUnmute: 'Включить уведомления',
  ReportSelectMessages: 'Выбрать сообщения',
  ParvaneAutoDelete: 'Автоудаление',
  ParvaneAutoDeleteOff: 'Выкл.',
  ParvaneAutoDelete1h: '1 час',
  ParvaneAutoDelete1d: '1 день',
  ParvaneAutoDelete1w: '1 неделя',
  'ChatList.Mute': 'Выключить уведомления',
  'ChatList.Unmute': 'Включить уведомления',
  lng_context_copy_image: 'Копировать изображение',
  lng_context_copy_text: 'Копировать текст',
  lng_context_copy_selected: 'Копировать выделенный текст',
  lng_context_copy_link: 'Копировать ссылку',
  lng_media_download: 'Скачать',
  lng_context_cancel_download: 'Отменить загрузку',
  lng_context_save_gif: 'Сохранить GIF',
  lng_polls_retract: 'Отозвать голос',
  Delete: 'Удалить',
  Edit: 'Изменить',
  MessageScheduleSend: 'Отправить сейчас',
  MessageScheduleEditTime: 'Изменить время',
  'MuteFor.Hours': {
    oneValue: 'Выключить на %@ час',
    fewValue: 'Выключить на %@ часа',
    manyValue: 'Выключить на %@ часов',
    otherValue: 'Выключить на %@ часов',
  },
  'MuteFor.Days': {
    oneValue: 'Выключить на %@ день',
    fewValue: 'Выключить на %@ дня',
    manyValue: 'Выключить на %@ дней',
    otherValue: 'Выключить на %@ дней',
  },
  'MuteFor.Forever': 'Выключить навсегда',
  'Common.Done': 'Готово',
  ParvaneCreatePack: 'Создать набор стикеров',
  ParvaneExportKeys: 'Экспорт ключей E2E',
  ParvaneImportKeys: 'Импорт ключей E2E',
  SessionsTitle: 'Устройства',
  ParvaneLinkPendingTitle: 'Перенос истории',
  ParvaneLinkPendingText: 'Ждём ваше другое устройство. Откройте там Настройки → Устройства и подтвердите код %@.',
  ParvaneLinkRequests: 'Запросы на перенос истории',
  ParvaneLinkOfferCode: 'Код: %@',
  ParvaneLinkConfirm: 'Перенести историю сообщений на это устройство? Убедитесь, что на нём показан код %@.',
  ParvaneLinkConfirmAction: 'Перенести',
  ParvaneLinkGranted: 'История перенесена',
  ParvaneLinkFailed: 'Не удалось перенести историю',
  ParvaneKeysPasswordPrompt: 'Пароль резервной копии',
  ParvaneKeysExported: 'Ключи E2E экспортированы',
  ParvaneKeysExportFailed: 'Не удалось экспортировать ключи E2E',
  ParvaneKeysImported: 'Ключи E2E импортированы, история синхронизируется заново',
  ParvaneKeysImportFailed: 'Не удалось импортировать ключи E2E',
  ParvanePackNamePrompt: 'Название набора стикеров',
  ParvanePackCreated: 'Набор стикеров создан: %@',
  ParvanePackCreateFailed: 'Не удалось создать набор стикеров',
  FilterNoChatsToDisplay: 'Чатов пока нет',
  'Chat.EmptyChat': 'Найдите контакт через поиск, чтобы начать общение',
  'ChatList.EmptyChatListFilterText': 'В этой папке пока нет подходящих чатов',
  'ChatList.EmptyChatListEditFilter': 'Изменить папку',
  NoMessages: 'Сообщений пока нет...',
  'Conversation.EmptyPlaceholder': 'Сообщений пока нет...',
  'Conversation.GreetingText': 'Отправьте сообщение, чтобы начать разговор',
  Close: 'Закрыть',
  lng_sure_logout: 'Вы действительно хотите выйти?',
  'AccountSettings.Logout': 'Выйти',
  AccDescrGoBack: 'Назад',

  Language: 'Язык',
  'Localization.InterfaceLanguage': 'Язык интерфейса',

  FilterEdit: 'Изменить папку',
  FilterChatTypes: 'Типы чатов',
  'ChatList.PeerTypeContact': 'контакт',
  'ChatList.PeerTypeNonContactUser': 'пользователь',
  'ChatList.PeerTypeBot': 'бот',
  FilterShowMoreChats: {
    oneValue: 'Показать ещё %@ чат',
    fewValue: 'Показать ещё %@ чата',
    manyValue: 'Показать ещё %@ чатов',
    otherValue: 'Показать ещё %@ чатов',
  },

  'Chat.DeleteMessagesConfirmation': {
    oneValue: 'Вы действительно хотите удалить это сообщение?',
    fewValue: 'Вы действительно хотите удалить эти сообщения?',
    manyValue: 'Вы действительно хотите удалить эти сообщения?',
    otherValue: 'Вы действительно хотите удалить эти сообщения?',
  },
  'Conversation.DeleteMessagesForEveryone': 'Удалить для всех',
  DeleteProceedBtn: 'Удалить',
  DeleteMessagesOptionAlso: 'Также удалить у %@',
  DeleteAdditionalActions: 'Дополнительно',
  DeleteAllFrom: 'Удалить все сообщения от %@',
  DeleteAllFromUsers: 'Удалить все сообщения этих пользователей',
  DeleteBan: 'Заблокировать %@',
  DeleteBanUsers: 'Заблокировать этих пользователей',
  DeleteRestrictUsers: 'Ограничить этих пользователей',
  KickFromSupergroup: 'Удалить из группы',
  ReportSpamTitle: 'Пожаловаться на спам',
  UserRestrictionsCanDoUsers: {
    oneValue: 'Что может этот пользователь?',
    fewValue: 'Что могут эти пользователи?',
    manyValue: 'Что могут эти пользователи?',
    otherValue: 'Что могут эти пользователи?',
  },
  lng_delete_for_everyone_hint: {
    oneValue: 'Сообщение будет удалено у всех участников чата.',
    fewValue: 'Сообщения будут удалены у всех участников чата.',
    manyValue: 'Сообщения будут удалены у всех участников чата.',
    otherValue: 'Сообщения будут удалены у всех участников чата.',
  },
  lng_delete_for_me_chat_hint: {
    oneValue: 'Сообщение будет удалено только у вас, у других участников оно останется.',
    fewValue: 'Сообщения будут удалены только у вас, у других участников они останутся.',
    manyValue: 'Сообщения будут удалены только у вас, у других участников они останутся.',
    otherValue: 'Сообщения будут удалены только у вас, у других участников они останутся.',
  },
  ClearHistoryMessageSingle: 'Вы действительно хотите очистить историю с %@?',
  ClearHistoryMyNotesMessage: 'Вы действительно хотите очистить свои заметки?',

  BlockUser: 'Заблокировать',
  'GroupInfo.DeleteAndExit': 'Удалить и выйти',
  'Common.Back': 'Назад',
  'Common.Close': 'Закрыть',
  'Channel.TitleInfo': 'О канале',
  'Group.Info.AdminLog': 'Недавние действия',
  lng_group_invite_title: 'Ссылки-приглашения',
  'Conversation.SearchPlaceholder': 'Поиск',
  Hide: 'Скрыть',
  MarkAllAsRead: 'Отметить всё как прочитанное',
  SavedOpenChat: 'Открыть чат',
  'Chat.Pinned.UnpinAll': {
    oneValue: 'Открепить %@ сообщение',
    fewValue: 'Открепить все %@ сообщения',
    manyValue: 'Открепить все %@ сообщений',
    otherValue: 'Открепить все %@ сообщений',
  },
  'Chat.PanelUnpinAllMessages': 'Открепить все сообщения',
  'Chat.UnpinAllMessagesConfirmation': {
    oneValue: 'Открепить %@ сообщение в этом чате?',
    fewValue: 'Открепить все %@ сообщения в этом чате?',
    manyValue: 'Открепить все %@ сообщений в этом чате?',
    otherValue: 'Открепить все %@ сообщений в этом чате?',
  },
  'Conversation.PinMessageAlert.PinAndNotifyMembers': 'Уведомить всех участников',
  'Share.Link.Copied': 'Ссылка скопирована в буфер обмена',
  lng_context_copy_selected_items: 'Копировать выбранное как текст',
  'Conversation.ReportMessages': 'Пожаловаться',
  ForwardedFrom: 'Переслано от',
  lng_context_forward_msg: 'Переслать сообщение',
  ReplyToQuote: 'Ответ %@',
  DoNotReply: 'Не отвечать',
  EditMessage: 'Изменить сообщение',
  ForwardAnotherChat: 'Переслать в другой чат',
  ForwardedMessageCount: {
    oneValue: '%@ пересланное сообщение',
    fewValue: '%@ пересланных сообщения',
    manyValue: '%@ пересланных сообщений',
    otherValue: '%@ пересланных сообщений',
  },
  'Message.Context.Goto': 'Показать сообщение',
  RemoveQuote: 'Убрать цитату',
  ReplyToAnotherChat: 'Ответить в другом чате',
  SendWhenOnline: 'Отправить, когда появится в сети',
  'Schedule.SendWhenOnline': 'Отправить, когда появится в сети',
  'Chat.PlayOnceVoiceMessageTooltip': 'Отправить для одноразового прослушивания',
  FilterByUser: 'Фильтр по отправителю',
  NoResult: 'Ничего не найдено',
  NoResultFoundFor: 'По запросу «%@» ничего не найдено',
  Of: '%1$d из %2$d',
  SearchAsChat: 'Показать как чат',
  SearchAsList: 'Показать списком',
  SearchMyMessages: 'Искать в моих сообщениях',
  SearchThisChat: 'Искать в этом чате',
  HashtagSearchPlaceholder: 'Поиск хэштегов',
  SearchHashtagsHint: 'Поиск хэштегов по сообщениям',
  'ChatList.Search.NoResults': 'Ничего не найдено',
  'ChatList.Search.NoResultsDescription': 'По вашему запросу ничего не найдено.\nПопробуйте другой запрос.',
  'Conversation.ContextViewReplies': {
    oneValue: 'Показать %@ ответ',
    fewValue: 'Показать %@ ответа',
    manyValue: 'Показать %@ ответов',
    otherValue: 'Показать %@ ответов',
  },
  MessageContainsEmojiPack: 'В сообщении есть эмодзи из набора **%@**.',
  MessageContainsEmojiPacks: {
    oneValue: 'В сообщении есть эмодзи из %@ набора.',
    fewValue: 'В сообщении есть эмодзи из %@ наборов.',
    manyValue: 'В сообщении есть эмодзи из %@ наборов.',
    otherValue: 'В сообщении есть эмодзи из %@ наборов.',
  },
  PmRead: 'Прочитано',
  PmReadAt: 'Прочитано %@',
  PmReadShowWhen: 'Показывать время прочтения',
  'Chat.PrivateMessageEditTimestamp.Date': 'Изменено %@',
  'Chat.EmptyStateIntroFooter': 'Напишите %@, чтобы начать разговор',
  'ScheduledMessages.EmptyPlaceholder': 'Отложенных сообщений пока нет...',
  'EmptyGroupInfo.Title': 'Вы создали группу',
  'EmptyGroupInfo.Subtitle': 'В группах доступны:',
  'EmptyGroupInfo.Line1': 'До 200 000 участников',
  'EmptyGroupInfo.Line2': 'Постоянная история чата',
  'EmptyGroupInfo.Line3': 'Ссылки-приглашения',
  'EmptyGroupInfo.Line4': 'Администраторы с разными правами',
  'Conversation.CloudStorageInfo.Title': 'Ваше облачное хранилище',
  'Conversation.ClousStorageInfo.Description1': 'Пересылайте сюда сообщения, чтобы сохранить их.',
  'Conversation.ClousStorageInfo.Description2': 'Отправляйте медиа и файлы, чтобы хранить их.',
  'Conversation.ClousStorageInfo.Description3': 'Открывайте этот чат с любого устройства.',
  'Conversation.ClousStorageInfo.Description4': 'Используйте поиск, чтобы быстро находить нужное.',

  Members: {
    oneValue: '%@ участник', fewValue: '%@ участника', manyValue: '%@ участников', otherValue: '%@ участников',
  },
  StatusHiddenShow: 'Показать',
  UsernameAlso: 'Также %USERNAMES%',
  SavedMessagesTab: 'Избранное',
  lng_media_audio_empty: 'Голосовых сообщений нет',
  lng_media_file_empty: 'Файлов нет',
  lng_media_gif_empty: 'GIF нет',
  lng_media_link_empty: 'Ссылок нет',
  lng_media_song_empty: 'Музыки нет',
  lng_new_contact_add: 'Добавить в контакты',
  lng_new_contact_block: 'Заблокировать',
  'UserInfo.BlockConfirmationTitle': 'Заблокировать %@?',
  SharedContactAdd: 'Добавить в контакты',
  SharedContactMessage: 'Написать',
  PhoneCopied: 'Телефон скопирован в буфер обмена',
  'UserInfo.FirstNamePlaceholder': 'Имя',
  'UserInfo.LastNamePlaceholder': 'Фамилия',
  Reset: 'Сбросить',
  Checking: 'Проверка...',
  UsernameCopied: 'Имя пользователя скопировано в буфер обмена',
  'ProfilePhoto.SetMainPhoto': 'Сделать основным фото',
  Confirm: 'Подтвердить',
  AreYouSure: 'Вы уверены?',
  'Preview.DeletePhoto': 'Удалить фото',
  ChannelHideMembers: 'Скрыть участников',
  'Channel.EditAdmin.Permission.BanUsers': 'Блокировка пользователей',
  ChatHistoryHiddenInfo2: 'Новые участники не увидят более ранние сообщения.',
  ChatHistoryVisibleInfo: 'Новые участники увидят сообщения, отправленные до их вступления.',
  'GroupInfo.InviteLinks': 'Ссылки-приглашения',
  ReactionsAll: 'Все',
  ReactionsOff: 'Выкл.',
  'Channel.DiscussionGroup.LinkGroup': 'Привязать группу',
  ChannelSignMessagesWithProfile: 'Показывать профили авторов',
  ChannelSignProfilesInfo: 'Добавлять имена администраторов к их сообщениям.',
  'InviteLink.InviteLink': 'Ссылка-приглашение',
  'InviteLink.Expired': 'Истекла',
  'InviteLink.ExpiresIn': 'истекает через %@',
  lng_create_permanent_link_title: 'Основная ссылка',
  lng_group_invite_expire_custom: 'Другое',
  lng_group_invite_usage_custom: 'Другое',
  'ChannelVisibility.Forwarding.Enabled': 'Участники могут пересылать сообщения из этой группы и сохранять медиа.',
  'ChannelVisibility.Forwarding.Disabled': 'Участники не могут пересылать сообщения из этой группы и сохранять медиа.',
  'ChannelVisibility.Forwarding.GroupInfo': 'Запретить сохранение контента',
  'ChannelVisibility.Forwarding.ChannelInfo': 'Запретить сохранение контента',
  AllReactions: 'Все реакции',
  SomeReactions: 'Некоторые реакции',
  NoReactions: 'Без реакций',
  AvailableReactions: 'Доступные реакции',
  OnlyAllowThisReactions: 'Разрешить только эти реакции',
  EnableAllReactionsInfo: 'Участники группы могут использовать любые эмодзи как реакции на сообщения.',
  EnableSomeReactionsInfo: 'Выберите эмодзи, которыми участники группы смогут реагировать на сообщения.',
  DisableReactionsInfo: 'Участники группы не могут ставить реакции на сообщения.',
  MaximumReactionsHeader: 'Максимум реакций на сообщение',
  'ChannelReactions.MaxCount.Info': 'Ограничить число разных реакций, которые можно поставить на одно сообщение.',
  'PeerInfo.AllowedReactions.MaxCountValue': '%@',

  'Stickers.AddToFavorites': 'В избранное',
  'Stickers.RemoveFromFavorites': 'Убрать из избранного',
  StickersCopy: 'Копировать ссылку',
  'StickerPack.StickerCount': {
    oneValue: '%@ стикер', fewValue: '%@ стикера', manyValue: '%@ стикеров', otherValue: '%@ стикеров',
  },
  SuggestAnimatedEmoji: 'Подсказывать эмодзи',
  EmojiBotInfo: 'Свои эмодзи берутся из установленных наборов стикеров.',
  lng_launch_exe_dont_ask: 'Больше не спрашивать',
  lng_launch_svg_warning: 'Этот файл может содержать код, выполняемый в браузере. Всё равно открыть?',
  'Video.Unsupported.Desktop': 'Ваш браузер не поддерживает это видео.',
  'Video.Unsupported.Mobile': 'Ваш браузер не поддерживает это видео.',
  i18n_dragToSort: 'Перетащите для сортировки',
  lng_context_archive_to_list: 'Вернуть в основной список',
  SearchEmptyViewTitle: 'Ничего не найдено',

  lng_call_accept: 'Принять',
  lng_call_screencast: 'Показать экран',
  lng_call_status_requesting: 'Соединение...',
  lng_call_status_ringing: 'Вызов...',
  lng_call_status_incoming: 'Входящий звонок',
  lng_call_status_waiting: 'Ожидание...',
  lng_call_status_exchanging: 'Обмен ключами шифрования...',
  lng_call_status_hanging: 'Завершение звонка...',
  lng_call_rate_label: 'Оцените звонок',
  lng_call_rate_comment: 'Что пошло не так?',
  lng_group_call_leave: 'Выйти',
  lng_group_call_settings: 'Настройки',
  AccDescrCollapsePanel: 'Свернуть панель',
  AccDescrExpandPanel: 'Развернуть панель',

  Calls: 'Звонки',
  'Privacy.ProfilePhoto': 'Фото профиля',
  PrivacyBio: 'О себе',
  lng_settings_experimental: 'Экспериментальные',
  lng_settings_title_chat_name: 'Название чата в заголовке окна',
  lng_settings_window_system: 'Системная рамка окна',
  lng_username_link: 'Ссылка',
  'ShortcutsController.Others.LockByPasscode': 'Заблокировать',
  AnonymousForward: 'Аноним',
  NewContact: 'Новый контакт',
  'Contacts.PhoneNumber.NotRegistred': 'Пользователя с таким ником нет.',
  'UserInfo.NotificationsEnabled': 'Включены',
  'UserInfo.NotificationsDisabled': 'Выключены',
  DeleteContact: 'Удалить контакт',
  ParvaneTwoFactorTitle: 'Двухфакторная аутентификация',
  ParvaneTwoFactorToggle: 'Подтверждать вход в Telegram',
  ParvaneTwoFactorInfo: 'После пароля каждое новое устройство нужно подтвердить в Telegram-аккаунте, '
    + 'привязанном к профилю.',
  ParvaneTwoFactorNoTelegram: 'Сначала привяжите Telegram: это происходит при подтверждении аккаунта через бота.',
  ParvaneTwoFactorFailed: 'Не удалось изменить настройку двухфакторного входа',
};

function isRussian(langCode: string) {
  return /^ru\b/i.test(langCode);
}

export function buildOldLangPack(langCode: string): ApiOldLangPack {
  const pack: ApiOldLangPack = {
    ...OLD_LANG_PACK_EN,
    ...(isRussian(langCode) ? OLD_LANG_PACK_RU : {}),
  };

  const longWeekday = new Intl.DateTimeFormat(langCode, { weekday: 'long' });
  const shortWeekday = new Intl.DateTimeFormat(langCode, { weekday: 'short' });
  // 2024-09-01 — воскресенье; идём по дням недели от него
  WEEKDAY_KEYS.forEach((key, day) => {
    const date = new Date(Date.UTC(2024, 8, 1 + day, 12));
    pack[`Weekday.${key}`] = longWeekday.format(date);
    pack[`Weekday.Short${key}`] = shortWeekday.format(date);
  });

  const longMonth = new Intl.DateTimeFormat(langCode, { month: 'long' });
  const shortMonth = new Intl.DateTimeFormat(langCode, { month: 'short' });
  // Родительный падеж («15 сентября»): берём часть month из формата «день месяц»
  const genitiveMonth = new Intl.DateTimeFormat(langCode, { day: 'numeric', month: 'long' });
  MONTH_KEYS.forEach((key, month) => {
    const date = new Date(Date.UTC(2024, month, 15, 12));
    pack[`Month.${key}`] = longMonth.format(date);
    pack[`Month.Short${key}`] = shortMonth.format(date);
    const genitive = genitiveMonth.formatToParts(date).find((part) => part.type === 'month')?.value;
    pack[`Month.Gen${key}`] = genitive || longMonth.format(date);
  });

  return pack;
}
