// Синтез минимального ApiOldLangPack для старого lang-провайдера. Без него
// легаси-форматтеры дат (список чатов, «был(а) в сети») показывают голые ключи
// вида `Weekday.ShortMonday`. Имена дней/месяцев берём из Intl — без сети.

import type { ApiOldLangPack } from '../types';

const WEEKDAY_KEYS = [
  'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
];

const MONTH_KEYS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export function buildOldLangPack(langCode: string): ApiOldLangPack {
  const pack: ApiOldLangPack = {
    Cancel: 'Cancel',
    DialogPin: 'Pin',
    DialogUnpin: 'Unpin',
    Forward: 'Forward',
    PinMessageAlertChat: 'Do you want to pin this message for both participants?',
    PinMessageAlertTitle: 'Pin Message',
    UnreadMessages: 'Unread Messages',
    'Conversation.PinMessagesFor': 'Also pin for %@',
    'Weekday.Today': 'Today',
    'Weekday.Yesterday': 'Yesterday',
    formatDateAtTime: '%1$s at %2$s',
    'Time.TodayAt': 'today at %@',
    'Time.YesterdayAt': 'yesterday at %@',
    'Time.AtDate': '%@',
    'Time.JustNow': 'just now',
    'Time.MinutesAgo': { oneValue: '%@ minute ago', otherValue: '%@ minutes ago' },
    'StickerPack.AddStickerCount': { oneValue: 'Add %@ Sticker', otherValue: 'Add %@ Stickers' },
    'StickerPack.RemoveStickerCount': { oneValue: 'Remove %@ Sticker', otherValue: 'Remove %@ Stickers' },
    SETTINGS: 'Settings',
    lng_settings_information: 'Edit profile',
    FirstName: 'First name (required)',
    LastName: 'Last name (optional)',
    UserBio: 'Bio (optional)',
    Save: 'Save',
    Username: 'Username',
    UsernameHelp: 'Usernames are not supported on this server yet.',
    lng_settings_about_bio: 'Any details such as age, occupation or city.',
    LogOutTitle: 'Log Out',
    'Common.Select': 'Select',
    'Chat.ForwardActionHeader': 'Forward',
    'AttachmentMenu.PhotoOrVideo': 'Photo or Video',
    AttachDocument: 'Document',
    lng_context_remove_from_group: 'Remove from group',
    'GroupRemoved.Remove': 'Remove user',
    'PeerInfo.Confirm.RemovePeer': 'Remove %@ from the group?',
    lng_box_remove: 'Remove',
    lng_channel_add_users: 'Add members',
    Online: 'online',
    Lately: 'last seen recently',
    'LastSeen.JustNow': 'last seen just now',
    'LastSeen.MinutesAgo': { oneValue: 'last seen %@ minute ago', otherValue: 'last seen %@ minutes ago' },
    'LastSeen.HoursAgo': { oneValue: 'last seen %@ hour ago', otherValue: 'last seen %@ hours ago' },
    'LastSeen.TodayAt': 'last seen today at %@',
    'LastSeen.YesterdayAt': 'last seen yesterday at %@',
    'LastSeen.AtDate': 'last seen %@',
    ScheduleMessage: 'Schedule Message',
    SendWithoutSound: 'Send Without Sound',
    'Conversation.ScheduleMessage.SendToday': 'Send today at %@',
    'Conversation.ScheduleMessage.SendOn': 'Send on %@ at %@',
    BlockedUsers: 'Blocked Users',
    SendMessage: 'Send Message',
    NewMessageTitle: 'New Message',
    GroupAddMembers: 'Add Members',
    Emoji: 'Emoji',
    AccDescrStickers: 'Stickers',
    AccDescrVoiceMessage: 'Record voice message',
    AccDescrVideoMessage: 'Record video message',
    AttachAudio: 'Voice Message',
    SharedMedia: 'Shared Media',
    SavedMessages: 'Saved Messages',
    CallMessageIncoming: 'Incoming Call',
    CallMessageOutgoing: 'Outgoing Call',
    CallMessageIncomingMissed: 'Missed Call',
    CallMessageOutgoingMissed: 'Canceled Call',
    CallMessageIncomingDeclined: 'Declined Call',
    CallMessageVideoIncoming: 'Incoming Video Call',
    CallMessageVideoOutgoing: 'Outgoing Video Call',
    CallMessageVideoIncomingMissed: 'Missed Video Call',
    CallMessageVideoOutgoingMissed: 'Canceled Video Call',
    CallMessageVideoIncomingDeclined: 'Declined Video Call',
    CallMessageWithDuration: '%1$@ (%2$@)',
    CallAgain: 'Call Again',
    CallBack: 'Call Back',
    VideoCall: 'Video Call',
    ParvaneGroupCall: 'Group Call',
    ChannelAdministrators: 'Administrators',
    ChannelCreator: 'Owner',
    ChannelAdmin: 'Admin',
    'Channel.Management.AddModerator': 'Add Admin',
    EditAdminPromotedBy: 'Promoted by',
    GroupMembers: 'Members',
    ChannelSubscribers: 'Subscribers',
    ChannelBlockedUsers: 'Removed users',
    ChannelPermissions: 'Permissions',
    GroupType: 'Group Type',
    ChannelType: 'Channel Type',
    Loading: 'Loading...',
    Search: 'Search',
    DeleteMega: 'Delete Group',
    DeleteGroupForAll: 'Delete for all members',
    DeleteForAll: 'Delete for everyone',
    ChannelDelete: 'Delete Channel',
    ChannelDeleteAlert: 'Wait! Deleting this channel will remove all subscribers '
      + 'and all messages will be lost. Delete the channel anyway?',
    ChannelLeaveAlert: 'Are you sure you want to leave this channel?',
    ChannelLeaveAlertWithName: 'Are you sure you want to leave %@?',
    LeaveChannel: 'Leave Channel',
    'Group.LeaveGroup': 'Leave Group',
    'ChannelIntro.CreateChannel': 'Create Channel',
    SendMessageTo: 'Send message to...',
    'Channel.LeaveChannel': 'Leave Channel',
    AreYouSureDeleteAndExit: 'Are you sure you want to delete and leave the group?',
    'ChatList.DeleteAndLeaveGroupConfirmation': 'Are you sure you want to leave and delete %@?',
    'ChatList.DeleteChatConfirmation': 'Are you sure you want to delete %@?',
    ParvaneCallBusy: 'Line busy',
    ParvaneCallMute: 'Mute',
    ParvaneCallUnmute: 'Unmute',
    ParvaneCallCameraOff: 'Turn camera off',
    ParvaneCallCameraOn: 'Turn camera on',
    GifsTab: 'GIFs',
    'StickersList.EmojiItem': 'Custom Emoji',
    Call: 'Call',
    CallAccept: 'Accept',
    CallEndCall: 'End Call',
    CallStatusRequesting: 'requesting...',
    CallStatusRinging: 'ringing...',
    CallStatusIncoming: 'is calling you...',
    CallStatusExchanging: 'exchanging encryption keys...',
    ParvaneCallSecurityError: 'Call security check failed',
    CallEmojiKeyTooltip: 'If these emoji match what %@ sees, this call is fully secure',
    lng_polls_stop: 'Stop poll',
    lng_polls_stop_warning: 'If you stop this poll now, nobody will be able to vote in it anymore',
    lng_polls_stop_sure: 'Stop poll',
    GroupName: 'Group name',
    EnterChannelName: 'Channel name',
    'GroupInfo.ParticipantCount': { oneValue: '%@ member', otherValue: '%@ members' },
    lng_info_user_title: 'User Info',
    lng_info_group_title: 'Group Info',
    'GroupInfo.Title': 'Group Info',
    BlockedUsersInfo: 'Blocked users cannot send you messages',
    NoBlocked: 'No blocked users yet',
    BlockContact: 'Block',
    Unblock: 'Unblock',
    'SharedMedia.EmptyTitle': 'No shared media yet',
    NewGroup: 'New Group',
    // Разделитель в авто-имени группы из участников («Alice & Bob»); без ключа
    // сырой текст попадал в НАЗВАНИЕ создаваемой группы
    'CreateGroup.PeersTitleLastDelimeter': ' & ',
    NewChannel: 'New Channel',
    StickersName: 'Stickers and Emoji',
    SuggestStickers: 'Sticker suggestions by emoji',
    'InstalledStickers.DynamicPackOrder': 'Dynamic pack order',
    'InstalledStickers.DynamicPackOrderInfo': 'Frequently used sticker packs move up automatically',
    ChooseStickerMyStickerSets: 'My sticker sets',
    StickersBotInfo: 'Create your own packs in Settings',
    DoubleTapSetting: 'Quick reaction',
    ChatsMute: 'Mute',
    ChatsUnmute: 'Unmute',
    ReportSelectMessages: 'Select Messages',
    ParvaneAutoDelete: 'Auto-Delete',
    ParvaneAutoDeleteOff: 'Off',
    ParvaneAutoDelete1h: '1 hour',
    ParvaneAutoDelete1d: '1 day',
    ParvaneAutoDelete1w: '1 week',
    'ChatList.Mute': 'Mute',
    'ChatList.Unmute': 'Unmute',
    lng_context_copy_image: 'Copy Image',
    lng_context_copy_text: 'Copy Text',
    lng_context_copy_selected: 'Copy Selected Text',
    lng_context_copy_link: 'Copy Link',
    lng_media_download: 'Download',
    lng_context_cancel_download: 'Cancel Download',
    lng_context_save_gif: 'Save GIF',
    lng_polls_retract: 'Retract Vote',
    Delete: 'Delete',
    Edit: 'Edit',
    MessageScheduleSend: 'Send Now',
    MessageScheduleEditTime: 'Reschedule',
    'MuteFor.Hours': { oneValue: 'Mute for %@ hour', otherValue: 'Mute for %@ hours' },
    'MuteFor.Days': { oneValue: 'Mute for %@ day', otherValue: 'Mute for %@ days' },
    'MuteFor.Forever': 'Mute forever',
    'Common.Done': 'Done',
    ParvaneCreatePack: 'Create Sticker Pack',
    ParvaneExportKeys: 'Export E2E Keys',
    ParvaneImportKeys: 'Import E2E Keys',
    ParvaneKeysPasswordPrompt: 'Backup password',
    ParvaneKeysExported: 'E2E keys exported',
    ParvaneKeysExportFailed: 'Could not export E2E keys',
    ParvaneKeysImported: 'E2E keys imported, resyncing history',
    ParvaneKeysImportFailed: 'Could not import E2E keys',
    ParvanePackNamePrompt: 'Sticker pack name',
    ParvanePackCreated: 'Sticker pack created: %@',
    ParvanePackCreateFailed: 'Could not create sticker pack',
    FilterNoChatsToDisplay: 'No chats yet',
    'Chat.EmptyChat': 'Start messaging by searching for a contact',
    'ChatList.EmptyChatListFilterText': 'No chats currently match this folder',
    'ChatList.EmptyChatListEditFilter': 'Edit Folder',
    NoMessages: 'No messages here yet...',
    'Conversation.EmptyPlaceholder': 'No messages here yet...',
    'Conversation.GreetingText': 'Send a message to start the conversation',
    Close: 'Close',
    lng_sure_logout: 'Are you sure you want to log out?',
    'AccountSettings.Logout': 'Log Out',
    AccDescrGoBack: 'Go back',
  };

  const longWeekday = new Intl.DateTimeFormat(langCode, { weekday: 'long' });
  const shortWeekday = new Intl.DateTimeFormat(langCode, { weekday: 'short' });
  // 2024-09-01 — воскресенье; идём по дням недели от него
  WEEKDAY_KEYS.forEach((key, day) => {
    const date = new Date(Date.UTC(2024, 8, 1 + day, 12));
    pack[`Weekday.${key}`] = longWeekday.format(date);
    pack[`Weekday.Short${key}`] = shortWeekday.format(date);
  });

  const longMonth = new Intl.DateTimeFormat(langCode, { month: 'long' });
  const shortMonth = new Intl.DateTimeFormat(langCode, { month: 'short' });
  MONTH_KEYS.forEach((key, month) => {
    const date = new Date(Date.UTC(2024, month, 15, 12));
    pack[`Month.${key}`] = longMonth.format(date);
    pack[`Month.Short${key}`] = shortMonth.format(date);
    pack[`Month.Gen${key}`] = longMonth.format(date);
  });

  return pack;
}
